volumes:
  server-db:
  server-data:

networks:
  default:
    driver: bridge

services:
  # Parchment backend server DB
  server-db:
    container_name: server-db
    image: postgres:latest
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - server-db:/var/lib/postgresql/data
    ports:
      - '5432:5432'
    restart: unless-stopped

  # Parchment backend (Elysia)
  server:
    container_name: parchment-server
    image: alexwohlbruck/parchment-server:latest
    environment:
      NODE_ENV: production
      DATABASE_URL: postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@server-db:5432/${POSTGRES_DB}
      SERVER_ORIGIN: ${SERVER_ORIGIN}
      CLIENT_ORIGIN: ${CLIENT_ORIGIN}
      GMAIL_EMAIL: ${GMAIL_EMAIL}
      GMAIL_APP_PASSWORD: ${GMAIL_APP_PASSWORD}
      APP_TESTER_EMAIL: ${APP_TESTER_EMAIL}
    ports:
      - '5000:5000'
    volumes:
      - server-data:/app/data
    depends_on:
      - server-db
    restart: unless-stopped

  # Web frontend (Vue)
  web:
    container_name: parchment-web
    image: alexwohlbruck/parchment-web:latest
    environment:
      VITE_SERVER_ORIGIN: ${SERVER_ORIGIN}
      VITE_PORT: ${VITE_PORT}
      VITE_MAPBOX_ACCESS_TOKEN: ${MAPBOX_ACCESS_TOKEN}
      VITE_TRANSITLAND_API_KEY: ${TRANSITLAND_API_KEY}
      VITE_MAPTILER_API_KEY: ${MAPTILER_API_KEY}
      VITE_MAPILLARY_ACCESS_TOKEN: ${MAPILLARY_ACCESS_TOKEN}
    ports:
      - '5173:5173'
    depends_on:
      - server
    restart: unless-stopped
