import {
  LayerType,
  MapEngine,
  MapboxLayerType,
  SourceType,
} from '@/types/map.types'
import type { Layer } from '@/types/map.types'
import { buildProxyUrl } from './helpers'
import { computed } from 'vue'

export const CYCLING_LAYERS = computed(
  (): Omit<Layer, 'id' | 'userId' | 'createdAt' | 'updatedAt'>[] => [
  // ── Cycling layers ──────────────────────────
  // Vector layers served from the bicycle_ways and bicycle_routes
  // Martin sources (PostGIS tables populated by osm2pgsql).
  // Green palette. Opaque solid lines. Theme-responsive (light/dark).
  // surface-aware: unpaved surfaces get a distinct dashed style.

  // ── Bicycle routes (relations: icn, ncn, rcn, lcn) ─────────
  // Rendered as transparent dotted green lines alongside roads.
  // Bicycle routes
  {
    name: 'Bike Routes',
    icon: 'BikeIcon',
    showInLayerSelector: true,
    visible: false,
    type: LayerType.CUSTOM,
    engine: [MapEngine.MAPBOX, MapEngine.MAPLIBRE],
    groupId: 'Cycling',
    order: 11,
    configuration: {
      id: 'bicycle-routes',
      type: MapboxLayerType.LINE,
      source: {
        id: 'bicycle-routes',
        type: SourceType.VECTOR,
        tiles: [buildProxyUrl.value('barrelman/bicycle_routes/{z}/{x}/{y}')],
        maxzoom: 14,
      },
      'source-layer': 'bicycle_routes',
      minzoom: 5,
      filter: ['!=', ['get', 'state'], 'proposed'],
      paint: {
        'line-color': [
          'match',
          ['get', 'network'],
          'icn',
          '#145a32',
          'ncn',
          '#1a7a3a',
          'rcn',
          '#276749',
          'lcn',
          '#2d8a4e',
          '#2d8a4e',
        ],
        'line-width': [
          'interpolate',
          ['exponential', 1.5],
          ['zoom'],
          5,
          1,
          8,
          1.5,
          10,
          2,
          12,
          3,
          14,
          4,
          16,
          5,
        ],
        'line-opacity': 0.3,
        'line-emissive-strength': 0.8,
      },
      layout: {
        'line-cap': 'round',
        'line-join': 'round',
      },
    },
  },

  // Dedicated cycleways (highway=cycleway) — casing (outline)
  {
    name: 'Cycleways',
    icon: 'BikeIcon',
    showInLayerSelector: true,
    visible: false,
    type: LayerType.CUSTOM,
    engine: [MapEngine.MAPBOX, MapEngine.MAPLIBRE],
    groupId: 'Cycling',
    order: 3,
    configuration: {
      id: 'bicycle-cycleways-casing',
      type: MapboxLayerType.LINE,
      source: {
        id: 'bicycle-ways',
        type: SourceType.VECTOR,
        tiles: [buildProxyUrl.value('barrelman/bicycle_ways/{z}/{x}/{y}')],
        maxzoom: 16,
      },
      'source-layer': 'bicycle_ways',
      minzoom: 10,
      filter: ['all', ['==', 'infra_type', 'cycleway'], ['!has', 'state']],
      paint: {
        'line-color': [
          'interpolate',
          ['linear'],
          ['measure-light', 'brightness'],
          0.25,
          '#1a2a1f',
          0.3,
          '#ffffff',
        ],
        'line-width': [
          'interpolate',
          ['linear'],
          ['zoom'],
          10,
          2.5,
          14,
          5,
          16,
          8,
        ],
        'line-opacity': 1,
        'line-emissive-strength': 0.5,
      },
      layout: {
        'line-cap': 'round',
        'line-join': 'round',
      },
    },
  },
  // Dedicated cycleways — fill (paved)
  {
    name: 'Cycleways',
    icon: 'BikeIcon',
    showInLayerSelector: false,
    visible: false,
    type: LayerType.CUSTOM,
    engine: [MapEngine.MAPBOX, MapEngine.MAPLIBRE],
    groupId: 'Cycling',
    order: 3,
    configuration: {
      id: 'bicycle-cycleways',
      type: MapboxLayerType.LINE,
      source: {
        id: 'bicycle-ways',
        type: SourceType.VECTOR,
        tiles: [buildProxyUrl.value('barrelman/bicycle_ways/{z}/{x}/{y}')],
        maxzoom: 16,
      },
      'source-layer': 'bicycle_ways',
      minzoom: 10,
      filter: [
        'all',
        ['==', 'infra_type', 'cycleway'],
        ['!has', 'state'],
        [
          '!in',
          'surface',
          'gravel',
          'dirt',
          'grass',
          'ground',
          'earth',
          'sand',
          'mud',
          'unpaved',
          'fine_gravel',
          'compacted',
        ],
      ],
      paint: {
        'line-color': '#1a7a3a',
        'line-width': [
          'interpolate',
          ['linear'],
          ['zoom'],
          10,
          1.5,
          14,
          3.5,
          16,
          6,
        ],
        'line-opacity': 1,
        'line-emissive-strength': 0.8,
      },
      layout: {
        'line-cap': 'round',
        'line-join': 'round',
      },
    },
  },
  // Dedicated cycleways — fill (unpaved surfaces)
  {
    name: 'Cycleways',
    icon: 'BikeIcon',
    showInLayerSelector: false,
    visible: false,
    type: LayerType.CUSTOM,
    engine: [MapEngine.MAPBOX, MapEngine.MAPLIBRE],
    groupId: 'Cycling',
    order: 3,
    configuration: {
      id: 'bicycle-cycleways-unpaved',
      type: MapboxLayerType.LINE,
      source: {
        id: 'bicycle-ways',
        type: SourceType.VECTOR,
        tiles: [buildProxyUrl.value('barrelman/bicycle_ways/{z}/{x}/{y}')],
        maxzoom: 16,
      },
      'source-layer': 'bicycle_ways',
      minzoom: 10,
      filter: [
        'all',
        ['==', 'infra_type', 'cycleway'],
        ['!has', 'state'],
        [
          'in',
          'surface',
          'gravel',
          'dirt',
          'grass',
          'ground',
          'earth',
          'sand',
          'mud',
          'unpaved',
          'fine_gravel',
          'compacted',
        ],
      ],
      paint: {
        'line-color': '#2d8a4e',
        'line-width': [
          'interpolate',
          ['linear'],
          ['zoom'],
          10,
          1.5,
          14,
          3.5,
          16,
          6,
        ],
        'line-dasharray': [4, 2],
        'line-opacity': 1,
        'line-emissive-strength': 0.8,
      },
      layout: {
        'line-cap': 'round',
        'line-join': 'round',
      },
    },
  },

  // Cycle tracks (physically separated, cycleway=track)
  {
    name: 'Cycle Tracks',
    icon: 'BikeIcon',
    showInLayerSelector: true,
    visible: false,
    type: LayerType.CUSTOM,
    engine: [MapEngine.MAPBOX, MapEngine.MAPLIBRE],
    groupId: 'Cycling',
    order: 4,
    configuration: {
      id: 'bicycle-tracks',
      type: MapboxLayerType.LINE,
      source: {
        id: 'bicycle-ways',
        type: SourceType.VECTOR,
        tiles: [buildProxyUrl.value('barrelman/bicycle_ways/{z}/{x}/{y}')],
        maxzoom: 16,
      },
      'source-layer': 'bicycle_ways',
      minzoom: 11,
      filter: ['all', ['==', 'infra_type', 'cycle_track'], ['!has', 'state']],
      paint: {
        'line-color': '#2d8a4e',
        'line-width': [
          'interpolate',
          ['linear'],
          ['zoom'],
          11,
          1.2,
          14,
          3,
          16,
          5,
        ],
        'line-opacity': 1,
        'line-emissive-strength': 0.8,
      },
      layout: {
        'line-cap': 'round',
        'line-join': 'round',
      },
    },
  },

  // Bike lanes — casing
  {
    name: 'Bike Lanes',
    icon: 'BikeIcon',
    showInLayerSelector: false,
    visible: false,
    type: LayerType.CUSTOM,
    engine: [MapEngine.MAPBOX, MapEngine.MAPLIBRE],
    groupId: 'Cycling',
    order: 5,
    configuration: {
      id: 'bicycle-lanes-casing',
      type: MapboxLayerType.LINE,
      source: {
        id: 'bicycle-ways',
        type: SourceType.VECTOR,
        tiles: [buildProxyUrl.value('barrelman/bicycle_ways/{z}/{x}/{y}')],
        maxzoom: 16,
      },
      'source-layer': 'bicycle_ways',
      minzoom: 12,
      filter: ['all', ['==', 'infra_type', 'cycle_lane'], ['!has', 'state']],
      paint: {
        'line-color': [
          'interpolate',
          ['linear'],
          ['measure-light', 'brightness'],
          0.25,
          '#1a2a1f',
          0.3,
          '#ffffff',
        ],
        'line-width': [
          'interpolate',
          ['linear'],
          ['zoom'],
          12,
          1,
          14,
          2.5,
          16,
          4.5,
        ],
        'line-opacity': 1,
        'line-emissive-strength': 0.5,
      },
      layout: {
        'line-cap': 'round',
        'line-join': 'round',
      },
    },
  },
  // Dedicated painted bike lanes (cycle_lane only)
  {
    name: 'Bike Lanes',
    icon: 'BikeIcon',
    showInLayerSelector: true,
    visible: false,
    type: LayerType.CUSTOM,
    engine: [MapEngine.MAPBOX, MapEngine.MAPLIBRE],
    groupId: 'Cycling',
    order: 5,
    configuration: {
      id: 'bicycle-lanes',
      type: MapboxLayerType.LINE,
      source: {
        id: 'bicycle-ways',
        type: SourceType.VECTOR,
        tiles: [buildProxyUrl.value('barrelman/bicycle_ways/{z}/{x}/{y}')],
        maxzoom: 16,
      },
      'source-layer': 'bicycle_ways',
      minzoom: 12,
      filter: ['all', ['==', 'infra_type', 'cycle_lane'], ['!has', 'state']],
      paint: {
        'line-color': '#38a169',
        'line-width': [
          'interpolate',
          ['linear'],
          ['zoom'],
          12,
          1,
          14,
          2.5,
          16,
          4.5,
        ],
        'line-dasharray': [0.1, 1.5],
        'line-opacity': 1,
        'line-emissive-strength': 0.8,
      },
      layout: {
        'line-cap': 'round',
        'line-join': 'round',
      },
    },
  },

  // Shared lanes (sharrows, shoulders, bus-lanes) — casing
  // Styled like bike routes: light, transparent. These are "intent" markings, not real infra.
  {
    name: 'Shared Lanes',
    icon: 'BikeIcon',
    showInLayerSelector: false,
    visible: false,
    type: LayerType.CUSTOM,
    engine: [MapEngine.MAPBOX, MapEngine.MAPLIBRE],
    groupId: 'Cycling',
    order: 5,
    configuration: {
      id: 'bicycle-shared-lanes-casing',
      type: MapboxLayerType.LINE,
      source: {
        id: 'bicycle-ways',
        type: SourceType.VECTOR,
        tiles: [buildProxyUrl.value('barrelman/bicycle_ways/{z}/{x}/{y}')],
        maxzoom: 16,
      },
      'source-layer': 'bicycle_ways',
      minzoom: 12,
      filter: [
        'all',
        [
          'in',
          'infra_type',
          'shared_lane',
          'opposite',
          'shoulder',
          'share_busway',
        ],
        ['!has', 'state'],
      ],
      paint: {
        'line-color': [
          'interpolate',
          ['linear'],
          ['measure-light', 'brightness'],
          0.25,
          '#1a2a1f',
          0.3,
          '#ffffff',
        ],
        'line-width': [
          'interpolate',
          ['linear'],
          ['zoom'],
          12,
          1,
          14,
          2.5,
          16,
          4.5,
        ],
        'line-opacity': 0.55,
        'line-emissive-strength': 0.5,
      },
      layout: {
        'line-cap': 'butt',
        'line-join': 'round',
      },
    },
  },
  // Shared lanes — fill
  {
    name: 'Shared Lanes',
    icon: 'BikeIcon',
    showInLayerSelector: true,
    visible: false,
    type: LayerType.CUSTOM,
    engine: [MapEngine.MAPBOX, MapEngine.MAPLIBRE],
    groupId: 'Cycling',
    order: 5,
    configuration: {
      id: 'bicycle-shared-lanes',
      type: MapboxLayerType.LINE,
      source: {
        id: 'bicycle-ways',
        type: SourceType.VECTOR,
        tiles: [buildProxyUrl.value('barrelman/bicycle_ways/{z}/{x}/{y}')],
        maxzoom: 16,
      },
      'source-layer': 'bicycle_ways',
      minzoom: 12,
      filter: [
        'all',
        [
          'in',
          'infra_type',
          'shared_lane',
          'opposite',
          'shoulder',
          'share_busway',
        ],
        ['!has', 'state'],
      ],
      paint: {
        'line-color': '#9ae6b4',
        'line-width': [
          'interpolate',
          ['linear'],
          ['zoom'],
          12,
          1,
          14,
          2.5,
          16,
          4.5,
        ],
        'line-dasharray': [2, 3],
        'line-opacity': 0.55,
        'line-emissive-strength': 0.8,
      },
      layout: {
        'line-cap': 'butt',
        'line-join': 'round',
      },
    },
  },

  // Bicycle paths (footway/path with bicycle=designated) — paved
  {
    name: 'Bicycle Paths',
    icon: 'BikeIcon',
    showInLayerSelector: true,
    visible: false,
    type: LayerType.CUSTOM,
    engine: [MapEngine.MAPBOX, MapEngine.MAPLIBRE],
    groupId: 'Cycling',
    order: 6,
    configuration: {
      id: 'bicycle-paths',
      type: MapboxLayerType.LINE,
      source: {
        id: 'bicycle-ways',
        type: SourceType.VECTOR,
        tiles: [buildProxyUrl.value('barrelman/bicycle_ways/{z}/{x}/{y}')],
        maxzoom: 16,
      },
      'source-layer': 'bicycle_ways',
      minzoom: 11,
      filter: [
        'all',
        ['in', 'infra_type', 'path_bicycle', 'steps_bicycle'],
        ['!has', 'state'],
        [
          '!in',
          'surface',
          'gravel',
          'dirt',
          'grass',
          'ground',
          'earth',
          'sand',
          'mud',
          'unpaved',
          'fine_gravel',
          'compacted',
        ],
      ],
      paint: {
        'line-color': '#2f855a',
        'line-width': [
          'interpolate',
          ['linear'],
          ['zoom'],
          11,
          1,
          14,
          2.5,
          16,
          4,
        ],
        'line-opacity': 1,
        'line-emissive-strength': 0.8,
      },
      layout: {
        'line-cap': 'round',
        'line-join': 'round',
      },
    },
  },
  // Bicycle paths — unpaved casing
  {
    name: 'Bicycle Paths',
    icon: 'BikeIcon',
    showInLayerSelector: false,
    visible: false,
    type: LayerType.CUSTOM,
    engine: [MapEngine.MAPBOX, MapEngine.MAPLIBRE],
    groupId: 'Cycling',
    order: 6,
    configuration: {
      id: 'bicycle-paths-unpaved-casing',
      type: MapboxLayerType.LINE,
      source: {
        id: 'bicycle-ways',
        type: SourceType.VECTOR,
        tiles: [buildProxyUrl.value('barrelman/bicycle_ways/{z}/{x}/{y}')],
        maxzoom: 16,
      },
      'source-layer': 'bicycle_ways',
      minzoom: 11,
      filter: [
        'all',
        ['in', 'infra_type', 'path_bicycle', 'steps_bicycle'],
        ['!has', 'state'],
        [
          'in',
          'surface',
          'gravel',
          'dirt',
          'grass',
          'ground',
          'earth',
          'sand',
          'mud',
          'unpaved',
          'fine_gravel',
          'compacted',
        ],
      ],
      paint: {
        'line-color': [
          'interpolate',
          ['linear'],
          ['measure-light', 'brightness'],
          0.25,
          '#1a2a1f',
          0.3,
          '#ffffff',
        ],
        'line-width': [
          'interpolate',
          ['linear'],
          ['zoom'],
          11,
          1,
          14,
          2.5,
          16,
          4,
        ],
        'line-opacity': 1,
        'line-emissive-strength': 0.5,
      },
      layout: {
        'line-cap': 'round',
        'line-join': 'round',
      },
    },
  },
  // Bicycle paths — unpaved
  {
    name: 'Bicycle Paths',
    icon: 'BikeIcon',
    showInLayerSelector: false,
    visible: false,
    type: LayerType.CUSTOM,
    engine: [MapEngine.MAPBOX, MapEngine.MAPLIBRE],
    groupId: 'Cycling',
    order: 6,
    configuration: {
      id: 'bicycle-paths-unpaved',
      type: MapboxLayerType.LINE,
      source: {
        id: 'bicycle-ways',
        type: SourceType.VECTOR,
        tiles: [buildProxyUrl.value('barrelman/bicycle_ways/{z}/{x}/{y}')],
        maxzoom: 16,
      },
      'source-layer': 'bicycle_ways',
      minzoom: 11,
      filter: [
        'all',
        ['in', 'infra_type', 'path_bicycle', 'steps_bicycle'],
        ['!has', 'state'],
        [
          'in',
          'surface',
          'gravel',
          'dirt',
          'grass',
          'ground',
          'earth',
          'sand',
          'mud',
          'unpaved',
          'fine_gravel',
          'compacted',
        ],
      ],
      paint: {
        'line-color': '#68d391',
        'line-width': [
          'interpolate',
          ['linear'],
          ['zoom'],
          11,
          1,
          14,
          2.5,
          16,
          4,
        ],
        'line-dasharray': [3, 2],
        'line-opacity': 1,
        'line-emissive-strength': 0.8,
      },
      layout: {
        'line-cap': 'round',
        'line-join': 'round',
      },
    },
  },

  // Bicycle roads & cycle streets
  {
    name: 'Bicycle Roads',
    icon: 'BikeIcon',
    showInLayerSelector: true,
    visible: false,
    type: LayerType.CUSTOM,
    engine: [MapEngine.MAPBOX, MapEngine.MAPLIBRE],
    groupId: 'Cycling',
    order: 7,
    configuration: {
      id: 'bicycle-roads',
      type: MapboxLayerType.LINE,
      source: {
        id: 'bicycle-ways',
        type: SourceType.VECTOR,
        tiles: [buildProxyUrl.value('barrelman/bicycle_ways/{z}/{x}/{y}')],
        maxzoom: 16,
      },
      'source-layer': 'bicycle_ways',
      minzoom: 12,
      filter: [
        'all',
        [
          'in',
          'infra_type',
          'bicycle_road',
          'cycle_street',
          'bicycle_designated',
        ],
        ['!has', 'state'],
      ],
      paint: {
        'line-color': '#276749',
        'line-width': [
          'interpolate',
          ['linear'],
          ['zoom'],
          12,
          1.2,
          14,
          3,
          16,
          5,
        ],
        'line-opacity': 1,
        'line-emissive-strength': 0.8,
      },
      layout: {
        'line-cap': 'round',
        'line-join': 'round',
      },
    },
  },

  // Bicycle permitted — casing
  {
    name: 'Bicycle Permitted',
    icon: 'BikeIcon',
    showInLayerSelector: false,
    visible: false,
    type: LayerType.CUSTOM,
    engine: [MapEngine.MAPBOX, MapEngine.MAPLIBRE],
    groupId: 'Cycling',
    order: 8,
    configuration: {
      id: 'bicycle-permitted-casing',
      type: MapboxLayerType.LINE,
      source: {
        id: 'bicycle-ways',
        type: SourceType.VECTOR,
        tiles: [buildProxyUrl.value('barrelman/bicycle_ways/{z}/{x}/{y}')],
        maxzoom: 16,
      },
      'source-layer': 'bicycle_ways',
      minzoom: 13,
      filter: ['all', ['==', 'infra_type', 'bicycle_yes'], ['!has', 'state']],
      paint: {
        'line-color': [
          'interpolate',
          ['linear'],
          ['measure-light', 'brightness'],
          0.25,
          '#1a2a1f',
          0.3,
          '#ffffff',
        ],
        'line-width': [
          'interpolate',
          ['linear'],
          ['zoom'],
          13,
          0.8,
          15,
          2,
          16,
          3.5,
        ],
        'line-opacity': 1,
        'line-emissive-strength': 0.5,
      },
      layout: {
        'line-cap': 'round',
        'line-join': 'round',
      },
    },
  },
  // Bicycle permitted (bicycle=yes on roads)
  {
    name: 'Bicycle Permitted',
    icon: 'BikeIcon',
    showInLayerSelector: true,
    visible: false,
    type: LayerType.CUSTOM,
    engine: [MapEngine.MAPBOX, MapEngine.MAPLIBRE],
    groupId: 'Cycling',
    order: 8,
    configuration: {
      id: 'bicycle-permitted',
      type: MapboxLayerType.LINE,
      source: {
        id: 'bicycle-ways',
        type: SourceType.VECTOR,
        tiles: [buildProxyUrl.value('barrelman/bicycle_ways/{z}/{x}/{y}')],
        maxzoom: 16,
      },
      'source-layer': 'bicycle_ways',
      minzoom: 13,
      filter: ['all', ['==', 'infra_type', 'bicycle_yes'], ['!has', 'state']],
      paint: {
        'line-color': '#9ae6b4',
        'line-width': [
          'interpolate',
          ['linear'],
          ['zoom'],
          13,
          0.8,
          15,
          2,
          16,
          3.5,
        ],
        'line-opacity': 1,
        'line-emissive-strength': 0.8,
      },
      layout: {
        'line-cap': 'round',
        'line-join': 'round',
      },
    },
  },

  // ── Proposed / Under construction bikeways ──────────────────
  // Proposed — casing
  {
    name: 'Proposed Bikeways',
    icon: 'BikeIcon',
    showInLayerSelector: false,
    visible: false,
    type: LayerType.CUSTOM,
    engine: [MapEngine.MAPBOX, MapEngine.MAPLIBRE],
    groupId: 'Cycling',
    order: 10,
    configuration: {
      id: 'bicycle-proposed-casing',
      type: MapboxLayerType.LINE,
      source: {
        id: 'bicycle-ways',
        type: SourceType.VECTOR,
        tiles: [buildProxyUrl.value('barrelman/bicycle_ways/{z}/{x}/{y}')],
        maxzoom: 16,
      },
      'source-layer': 'bicycle_ways',
      minzoom: 11,
      filter: ['==', 'state', 'proposed'],
      paint: {
        'line-color': [
          'interpolate',
          ['linear'],
          ['measure-light', 'brightness'],
          0.25,
          '#261a36',
          0.3,
          '#9c7ec4',
        ],
        'line-width': [
          'interpolate',
          ['linear'],
          ['zoom'],
          11,
          0.8,
          14,
          1.5,
          16,
          2.5,
        ],
        'line-opacity': 1,
        'line-emissive-strength': 0.5,
      },
      layout: {
        'line-cap': 'round',
        'line-join': 'round',
      },
    },
  },
  // Proposed bikeways
  {
    name: 'Proposed Bikeways',
    icon: 'BikeIcon',
    showInLayerSelector: true,
    visible: false,
    type: LayerType.CUSTOM,
    engine: [MapEngine.MAPBOX, MapEngine.MAPLIBRE],
    groupId: 'Cycling',
    order: 10,
    configuration: {
      id: 'bicycle-proposed',
      type: MapboxLayerType.LINE,
      source: {
        id: 'bicycle-ways',
        type: SourceType.VECTOR,
        tiles: [buildProxyUrl.value('barrelman/bicycle_ways/{z}/{x}/{y}')],
        maxzoom: 16,
      },
      'source-layer': 'bicycle_ways',
      minzoom: 11,
      filter: ['==', 'state', 'proposed'],
      paint: {
        'line-color': '#873beb',
        'line-width': [
          'interpolate',
          ['linear'],
          ['zoom'],
          11,
          0.8,
          14,
          1.5,
          16,
          2.5,
        ],
        'line-dasharray': [1, 3],
        'line-opacity': 1,
        'line-emissive-strength': 0.8,
      },
      layout: {
        'line-cap': 'round',
        'line-join': 'round',
      },
    },
  },
  // Under construction — casing
  {
    name: 'Proposed Bikeways',
    icon: 'BikeIcon',
    showInLayerSelector: false,
    visible: false,
    type: LayerType.CUSTOM,
    engine: [MapEngine.MAPBOX, MapEngine.MAPLIBRE],
    groupId: 'Cycling',
    order: 10,
    configuration: {
      id: 'bicycle-construction-casing',
      type: MapboxLayerType.LINE,
      source: {
        id: 'bicycle-ways',
        type: SourceType.VECTOR,
        tiles: [buildProxyUrl.value('barrelman/bicycle_ways/{z}/{x}/{y}')],
        maxzoom: 16,
      },
      'source-layer': 'bicycle_ways',
      minzoom: 11,
      filter: ['==', 'state', 'construction'],
      paint: {
        'line-color': [
          'interpolate',
          ['linear'],
          ['measure-light', 'brightness'],
          0.25,
          '#1a2a1f',
          0.3,
          '#f79107',
        ],
        'line-width': [
          'interpolate',
          ['linear'],
          ['zoom'],
          11,
          1,
          14,
          2,
          16,
          3,
        ],
        'line-opacity': 0.8,
        'line-emissive-strength': 0.5,
      },
      layout: {
        'line-cap': 'round',
        'line-join': 'round',
      },
    },
  },
  // Under construction bikeways
  {
    name: 'Proposed Bikeways',
    icon: 'BikeIcon',
    showInLayerSelector: false,
    visible: false,
    type: LayerType.CUSTOM,
    engine: [MapEngine.MAPBOX, MapEngine.MAPLIBRE],
    groupId: 'Cycling',
    order: 10,
    configuration: {
      id: 'bicycle-construction',
      type: MapboxLayerType.LINE,
      source: {
        id: 'bicycle-ways',
        type: SourceType.VECTOR,
        tiles: [buildProxyUrl.value('barrelman/bicycle_ways/{z}/{x}/{y}')],
        maxzoom: 16,
      },
      'source-layer': 'bicycle_ways',
      minzoom: 11,
      filter: ['==', 'state', 'construction'],
      paint: {
        'line-color': '#FC8',
        'line-width': [
          'interpolate',
          ['linear'],
          ['zoom'],
          11,
          1,
          14,
          2,
          16,
          3,
        ],
        'line-dasharray': [0.2, 2],
        'line-opacity': 0.8,
        'line-emissive-strength': 0.8,
      },
      layout: {
        'line-cap': 'round',
        'line-join': 'round',
      },
    },
  },
  // Bicycle route labels
  {
    name: 'Bike Routes',
    icon: 'BikeIcon',
    showInLayerSelector: false,
    visible: false,
    type: LayerType.CUSTOM,
    engine: [MapEngine.MAPBOX, MapEngine.MAPLIBRE],
    groupId: 'Cycling',
    order: 11,
    configuration: {
      id: 'bicycle-routes-labels',
      type: MapboxLayerType.SYMBOL,
      source: {
        id: 'bicycle-routes',
        type: SourceType.VECTOR,
        tiles: [buildProxyUrl.value('barrelman/bicycle_routes/{z}/{x}/{y}')],
        maxzoom: 14,
      },
      'source-layer': 'bicycle_routes',
      minzoom: 10,
      filter: ['any', ['has', 'name'], ['has', 'ref']],
      paint: {
        'text-color': [
          'interpolate',
          ['linear'],
          ['measure-light', 'brightness'],
          0.25,
          '#4ade80',
          0.3,
          '#1a7a3a',
        ],
        'text-halo-color': [
          'interpolate',
          ['linear'],
          ['measure-light', 'brightness'],
          0.25,
          '#0a1f14',
          0.3,
          '#ffffff',
        ],
        'text-halo-width': 1.5,
        'text-emissive-strength': 0.8,
      },
      layout: {
        'symbol-placement': 'line',
        'text-field': ['coalesce', ['get', 'ref'], ['get', 'name']],
        'text-size': ['interpolate', ['linear'], ['zoom'], 10, 10, 14, 13],
        'text-max-angle': 30,
        'text-padding': 30,
        'text-letter-spacing': 0.05,
      },
    },
  },
])
