import {
  LayerType,
  MapEngine,
  MapboxLayerType,
  SourceType,
} from '@/types/map.types'
import type { Layer } from '@/types/map.types'
import { buildProxyUrl } from './helpers'
import { computed } from 'vue'

export const MAPILLARY_LAYERS = computed(
  (): Omit<Layer, 'id' | 'userId' | 'createdAt' | 'updatedAt'>[] => [
  {
    name: 'Mapillary Overview',
    icon: 'CameraIcon',
    showInLayerSelector: true,
    visible: false,
    type: LayerType.STREET_VIEW,
    engine: [MapEngine.MAPBOX, MapEngine.MAPLIBRE],
    groupId: 'Mapillary',
    order: 0,
    configuration: {
      id: 'mapillary-overview',
      type: MapboxLayerType.CIRCLE,
      slot: 'middle',
      source: {
        id: 'mapillary-overview',
        type: SourceType.VECTOR,
        tiles: [
          buildProxyUrl.value('mapillary/mly1_computed_public/2/{z}/{x}/{y}'),
        ],
        minzoom: 0,
        maxzoom: 5,
      },
      'source-layer': 'images',
      paint: {
        'circle-color': '#04CB63',
        'circle-radius': 4,
        'circle-opacity': 1,
        'circle-stroke-color': '#04CB63',
        'circle-stroke-width': 1.5,
        'circle-stroke-opacity': 0.7,
        'circle-emissive-strength': 1,
      },
    },
  },
  {
    name: 'Mapillary Sequences',
    icon: 'CameraIcon',
    showInLayerSelector: true,
    visible: false,
    type: LayerType.STREET_VIEW,
    engine: [MapEngine.MAPBOX, MapEngine.MAPLIBRE],
    groupId: 'Mapillary',
    order: 1,
    configuration: {
      id: 'mapillary-sequence',
      type: MapboxLayerType.LINE,
      slot: 'middle',
      source: {
        id: 'mapillary-sequence',
        type: SourceType.VECTOR,
        tiles: [
          buildProxyUrl.value('mapillary/mly1_computed_public/2/{z}/{x}/{y}'),
        ],
        minzoom: 6,
        maxzoom: 14,
      },
      'source-layer': 'sequence',
      paint: {
        'line-color': '#04CB63',
        'line-opacity': [
          'interpolate',
          ['linear'],
          ['zoom'],
          6,
          0,
          14,
          1,
          22,
          0.5,
        ],
        'line-width': [
          'interpolate',
          ['linear'],
          ['zoom'],
          6,
          0,
          7,
          1,
          14,
          2,
        ],
        'line-emissive-strength': 1,
      },
      layout: {
        'line-cap': 'round',
        'line-join': 'round',
      },
    },
  },
  {
    name: 'Mapillary Images',
    icon: 'CameraIcon',
    showInLayerSelector: true,
    visible: false,
    type: LayerType.STREET_VIEW,
    engine: [MapEngine.MAPBOX, MapEngine.MAPLIBRE],
    groupId: 'Mapillary',
    order: 2,
    configuration: {
      id: 'mapillary-image',
      type: MapboxLayerType.CIRCLE,
      slot: 'middle',
      source: {
        id: 'mapillary-image',
        type: SourceType.VECTOR,
        tiles: [
          buildProxyUrl.value('mapillary/mly1_computed_public/2/{z}/{x}/{y}'),
        ],
        minzoom: 6,
        maxzoom: 14,
      },
      'source-layer': 'image',
      paint: {
        'circle-color': '#04CB63',
        'circle-radius': [
          'interpolate',
          ['linear'],
          ['zoom'],
          14,
          0,
          16,
          3,
          22,
          6,
        ],
        'circle-opacity': 1,
        'circle-stroke-color': '#04CB63',
        'circle-stroke-width': [
          'interpolate',
          ['linear'],
          ['zoom'],
          14,
          0,
          16,
          2,
        ],
        'circle-stroke-opacity': 0.7,
        'circle-emissive-strength': 1,
      },
    },
  },
])
