import {
  LayerType,
  MapEngine,
  MapboxLayerType,
  SourceType,
} from '@/types/map.types'
import type { Layer } from '@/types/map.types'
import { buildProxyUrl } from './helpers'
import { computed } from 'vue'

export const TRANSIT_LAYERS = computed(
  (): Omit<Layer, 'id' | 'userId' | 'createdAt' | 'updatedAt'>[] => [
  // Transitland Route Active (hitbox/hover layer)
  {
    name: 'Route Active',
    icon: 'TrainIcon',
    showInLayerSelector: false,
    visible: false,
    type: LayerType.TRANSIT,
    engine: [MapEngine.MAPBOX, MapEngine.MAPLIBRE],
    order: 1,
    groupId: 'Transit',
    configuration: {
      id: 'transitland-route-active',
      type: MapboxLayerType.LINE,
      slot: 'middle',
      source: {
        id: 'transitland',
        type: SourceType.VECTOR,
        tiles: [buildProxyUrl.value('transitland/routes/{z}/{x}/{y}')],
        maxzoom: 14,
      },
      'source-layer': 'routes',
      layout: {
        'line-cap': 'round',
        'line-join': 'round',
      },
      paint: {
        'line-emissive-strength': 1,
        'line-color': '#ffff66',
        'line-width': 12,
        'line-opacity': [
          'case',
          ['boolean', ['feature-state', 'hover'], false],
          1.0,
          0.0,
        ],
      },
    },
  },
  // Rail Outline (route_type 2)
  {
    name: 'Rail Outline',
    icon: 'TrainIcon',
    showInLayerSelector: false,
    visible: false,
    type: LayerType.TRANSIT,
    engine: [MapEngine.MAPBOX, MapEngine.MAPLIBRE],
    order: 2,
    groupId: 'Transit',
    configuration: {
      id: 'transitland-rail-outline',
      type: MapboxLayerType.LINE,
      slot: 'middle',
      source: {
        id: 'transitland',
        type: SourceType.VECTOR,
        tiles: [buildProxyUrl.value('transitland/routes/{z}/{x}/{y}')],
        maxzoom: 14,
      },
      'source-layer': 'routes',
      filter: ['all', ['==', 'route_type', 2]],
      layout: {
        'line-cap': 'round',
        'line-join': 'round',
      },
      paint: {
        'line-emissive-strength': 0.2,
        'line-width': 3.0,
        'line-gap-width': 1.0,
        'line-color': '#ffffff',
      },
    },
  },
  // Rail (route_type < 3)
  {
    name: 'Rail',
    icon: 'TrainIcon',
    showInLayerSelector: false,
    visible: false,
    type: LayerType.TRANSIT,
    engine: [MapEngine.MAPBOX, MapEngine.MAPLIBRE],
    order: 3,
    groupId: 'Transit',
    configuration: {
      id: 'transitland-rail',
      type: MapboxLayerType.LINE,
      slot: 'middle',
      source: {
        id: 'transitland',
        type: SourceType.VECTOR,
        tiles: [buildProxyUrl.value('transitland/routes/{z}/{x}/{y}')],
        maxzoom: 14,
      },
      'source-layer': 'routes',
      filter: ['all', ['<', 'route_type', 3]],
      layout: {
        'line-cap': 'round',
        'line-join': 'round',
      },
      paint: {
        'line-emissive-strength': 1,
        'line-width': 3.0,
        'line-color': '#666666',
      },
    },
  },
  // Bus Low Outline
  {
    name: 'Bus Low Outline',
    icon: 'TrainIcon',
    showInLayerSelector: false,
    visible: false,
    type: LayerType.TRANSIT,
    engine: [MapEngine.MAPBOX, MapEngine.MAPLIBRE],
    order: 4,
    groupId: 'Transit',
    configuration: {
      id: 'transitland-bus-low-outline',
      type: MapboxLayerType.LINE,
      slot: 'middle',
      source: {
        id: 'transitland',
        type: SourceType.VECTOR,
        tiles: [buildProxyUrl.value('transitland/routes/{z}/{x}/{y}')],
        maxzoom: 14,
      },
      'source-layer': 'routes',
      filter: [
        'all',
        ['==', 'route_type', 3],
        ['any', ['<=', 'headway_secs', 0], ['>', 'headway_secs', 1260]],
      ],
      layout: {
        'line-cap': 'round',
        'line-join': 'round',
      },
      paint: {
        'line-emissive-strength': 0.2,
        'line-width': 1.5,
        'line-gap-width': 0.5,
        'line-color': '#ffffff',
      },
    },
  },
  // Bus Low/Unknown
  {
    name: 'Bus Low',
    icon: 'TrainIcon',
    showInLayerSelector: false,
    visible: false,
    type: LayerType.TRANSIT,
    engine: [MapEngine.MAPBOX, MapEngine.MAPLIBRE],
    order: 5,
    groupId: 'Transit',
    configuration: {
      id: 'transitland-bus-low',
      type: MapboxLayerType.LINE,
      slot: 'middle',
      source: {
        id: 'transitland',
        type: SourceType.VECTOR,
        tiles: [buildProxyUrl.value('transitland/routes/{z}/{x}/{y}')],
        maxzoom: 14,
      },
      'source-layer': 'routes',
      filter: [
        'all',
        ['==', 'route_type', 3],
        ['any', ['<=', 'headway_secs', 0], ['>', 'headway_secs', 1260]],
      ],
      layout: {
        'line-cap': 'round',
        'line-join': 'round',
      },
      paint: {
        'line-emissive-strength': 1,
        'line-width': 1.5,
        'line-color': '#8acaeb',
      },
    },
  },
  // Bus Medium/High Outline
  {
    name: 'Bus Medium Outline',
    icon: 'TrainIcon',
    showInLayerSelector: false,
    visible: false,
    type: LayerType.TRANSIT,
    engine: [MapEngine.MAPBOX, MapEngine.MAPLIBRE],
    order: 6,
    groupId: 'Transit',
    configuration: {
      id: 'transitland-bus-medium-outline',
      type: MapboxLayerType.LINE,
      slot: 'middle',
      source: {
        id: 'transitland',
        type: SourceType.VECTOR,
        tiles: [buildProxyUrl.value('transitland/routes/{z}/{x}/{y}')],
        maxzoom: 14,
      },
      'source-layer': 'routes',
      filter: [
        'all',
        ['==', 'route_type', 3],
        ['<=', 'headway_secs', 1260],
        ['>', 'headway_secs', 0],
      ],
      layout: {
        'line-cap': 'round',
        'line-join': 'round',
      },
      paint: {
        'line-emissive-strength': 0.2,
        'line-width': 2.0,
        'line-gap-width': 1.0,
        'line-color': '#ffffff',
      },
    },
  },
  // Bus Medium/High
  {
    name: 'Bus Medium',
    icon: 'TrainIcon',
    showInLayerSelector: false,
    visible: false,
    type: LayerType.TRANSIT,
    engine: [MapEngine.MAPBOX, MapEngine.MAPLIBRE],
    order: 7,
    groupId: 'Transit',
    configuration: {
      id: 'transitland-bus-medium',
      type: MapboxLayerType.LINE,
      slot: 'middle',
      source: {
        id: 'transitland',
        type: SourceType.VECTOR,
        tiles: [buildProxyUrl.value('transitland/routes/{z}/{x}/{y}')],
        maxzoom: 14,
      },
      'source-layer': 'routes',
      filter: [
        'all',
        ['==', 'route_type', 3],
        ['<=', 'headway_secs', 1260],
        ['>', 'headway_secs', 0],
      ],
      layout: {
        'line-cap': 'round',
        'line-join': 'round',
      },
      paint: {
        'line-emissive-strength': 1,
        'line-width': 2.0,
        'line-color': '#1c96d6',
      },
    },
  },
  // Tram Outline (route_type 0)
  {
    name: 'Tram Outline',
    icon: 'TrainIcon',
    showInLayerSelector: false,
    visible: false,
    type: LayerType.TRANSIT,
    engine: [MapEngine.MAPBOX, MapEngine.MAPLIBRE],
    order: 8,
    groupId: 'Transit',
    configuration: {
      id: 'transitland-tram-outline',
      type: MapboxLayerType.LINE,
      slot: 'middle',
      source: {
        id: 'transitland',
        type: SourceType.VECTOR,
        tiles: [buildProxyUrl.value('transitland/routes/{z}/{x}/{y}')],
        maxzoom: 14,
      },
      'source-layer': 'routes',
      filter: ['all', ['==', 'route_type', 0]],
      layout: {
        'line-cap': 'round',
        'line-join': 'round',
      },
      paint: {
        'line-emissive-strength': 0.2,
        'line-width': 3.0,
        'line-gap-width': 1.0,
        'line-color': '#ffffff',
      },
    },
  },
  // Tram (route_type 0)
  {
    name: 'Tram',
    icon: 'TrainIcon',
    showInLayerSelector: true,
    visible: false,
    type: LayerType.TRANSIT,
    engine: [MapEngine.MAPBOX, MapEngine.MAPLIBRE],
    order: 9,
    groupId: 'Transit',
    configuration: {
      id: 'transitland-tram',
      type: MapboxLayerType.LINE,
      slot: 'middle',
      source: {
        id: 'transitland',
        type: SourceType.VECTOR,
        tiles: [buildProxyUrl.value('transitland/routes/{z}/{x}/{y}')],
        maxzoom: 14,
      },
      'source-layer': 'routes',
      filter: ['all', ['==', 'route_type', 0]],
      layout: {
        'line-cap': 'round',
        'line-join': 'round',
      },
      paint: {
        'line-emissive-strength': 1,
        'line-width': 3.0,
        'line-color': ['coalesce', ['get', 'route_color'], '#ff9966'],
      },
    },
  },
  // Metro Outline (route_type 1)
  {
    name: 'Metro Outline',
    icon: 'TrainIcon',
    showInLayerSelector: false,
    visible: false,
    type: LayerType.TRANSIT,
    engine: [MapEngine.MAPBOX, MapEngine.MAPLIBRE],
    order: 10,
    groupId: 'Transit',
    configuration: {
      id: 'transitland-metro-outline',
      type: MapboxLayerType.LINE,
      slot: 'middle',
      source: {
        id: 'transitland',
        type: SourceType.VECTOR,
        tiles: [buildProxyUrl.value('transitland/routes/{z}/{x}/{y}')],
        maxzoom: 14,
      },
      'source-layer': 'routes',
      filter: ['all', ['==', 'route_type', 1]],
      layout: {
        'line-cap': 'round',
        'line-join': 'round',
      },
      paint: {
        'line-emissive-strength': 0.2,
        'line-width': 3.0,
        'line-gap-width': 1.0,
        'line-color': '#ffffff',
      },
    },
  },
  // Metro (route_type 1)
  {
    name: 'Metro',
    icon: 'TrainIcon',
    showInLayerSelector: true,
    visible: false,
    type: LayerType.TRANSIT,
    engine: [MapEngine.MAPBOX, MapEngine.MAPLIBRE],
    order: 11,
    groupId: 'Transit',
    configuration: {
      id: 'transitland-metro',
      type: MapboxLayerType.LINE,
      slot: 'middle',
      source: {
        id: 'transitland',
        type: SourceType.VECTOR,
        tiles: [buildProxyUrl.value('transitland/routes/{z}/{x}/{y}')],
        maxzoom: 14,
      },
      'source-layer': 'routes',
      filter: ['all', ['==', 'route_type', 1]],
      layout: {
        'line-cap': 'round',
        'line-join': 'round',
      },
      paint: {
        'line-emissive-strength': 1,
        'line-width': 3.0,
        'line-color': ['coalesce', ['get', 'route_color'], '#ff0000'],
      },
    },
  },
  // Other Routes Outline (route_type > 3)
  {
    name: 'Other Routes Outline',
    icon: 'TrainIcon',
    showInLayerSelector: false,
    visible: false,
    type: LayerType.TRANSIT,
    engine: [MapEngine.MAPBOX, MapEngine.MAPLIBRE],
    order: 12,
    groupId: 'Transit',
    configuration: {
      id: 'transitland-other-outline',
      type: MapboxLayerType.LINE,
      slot: 'middle',
      source: {
        id: 'transitland',
        type: SourceType.VECTOR,
        tiles: [buildProxyUrl.value('transitland/routes/{z}/{x}/{y}')],
        maxzoom: 14,
      },
      'source-layer': 'routes',
      filter: ['all', ['>', 'route_type', 3]],
      layout: {
        'line-cap': 'round',
        'line-join': 'round',
      },
      paint: {
        'line-width': [
          'step',
          ['get', 'headway_secs'],
          1.5,
          1,
          2.5,
          600,
          1.5,
          1200,
          1.5,
        ],
        'line-gap-width': [
          'step',
          ['get', 'headway_secs'],
          0.5,
          1,
          1.0,
          600,
          0.5,
          1200,
          0.5,
        ],
        'line-color': '#ffffff',
        'line-emissive-strength': 0.2,
      },
    },
  },
  // Other Routes (route_type > 3)
  {
    name: 'Other Routes',
    icon: 'TrainIcon',
    showInLayerSelector: true,
    visible: false,
    type: LayerType.TRANSIT,
    engine: [MapEngine.MAPBOX, MapEngine.MAPLIBRE],
    order: 13,
    groupId: 'Transit',
    configuration: {
      id: 'transitland-other',
      type: MapboxLayerType.LINE,
      slot: 'middle',
      source: {
        id: 'transitland',
        type: SourceType.VECTOR,
        tiles: [buildProxyUrl.value('transitland/routes/{z}/{x}/{y}')],
        maxzoom: 14,
      },
      'source-layer': 'routes',
      filter: ['all', ['>', 'route_type', 3]],
      layout: {
        'line-cap': 'round',
        'line-join': 'round',
      },
      paint: {
        'line-opacity': 1.0,
        'line-width': [
          'step',
          ['get', 'headway_secs'],
          1,
          1,
          2,
          600,
          1,
          1200,
          1,
        ],
        'line-color': '#E6A615',
        'line-emissive-strength': 1,
      },
    },
  },
  // Route Labels - Tram
  {
    name: 'Tram Labels',
    icon: 'TrainIcon',
    showInLayerSelector: false, // Managed with tram layer
    visible: false,
    type: LayerType.TRANSIT,
    engine: [MapEngine.MAPBOX, MapEngine.MAPLIBRE],
    order: 16,
    groupId: 'Transit',
    configuration: {
      id: 'transitland-tram-labels',
      type: MapboxLayerType.SYMBOL,
      slot: 'top',
      source: {
        id: 'transitland',
        type: SourceType.VECTOR,
        tiles: [buildProxyUrl.value('transitland/routes/{z}/{x}/{y}')],
        maxzoom: 14,
      },
      'source-layer': 'routes',
      filter: ['all', ['==', 'route_type', 0]],
      minzoom: 12, // Only show labels at higher zoom levels
      layout: {
        'symbol-placement': 'line',
        'text-field': [
          'case',
          ['!=', ['get', 'route_long_name'], ''],
          ['get', 'route_long_name'],
          ['!=', ['get', 'route_short_name'], ''],
          ['get', 'route_short_name'],
          '',
        ],
        'text-font': [
          ['concat', ['config', 'font'], ' Bold'],
          'DIN Pro',
          'Inter',
          'Arial Unicode MS Bold',
        ],
        'text-size': [
          'interpolate',
          ['linear'],
          ['zoom'],
          12,
          10,
          14,
          11,
          16,
          12,
          18,
          13,
        ],
        'text-rotation-alignment': 'map',
        'text-pitch-alignment': 'viewport',
        'symbol-spacing': 400,
        'text-max-angle': 30,
        'text-allow-overlap': false,
        'text-ignore-placement': false,
      },
      paint: {
        'text-color': [
          'case',
          [
            'all',
            ['!=', ['get', 'route_color'], ''],
            ['!=', ['get', 'route_color'], '#000'],
            ['!=', ['get', 'route_color'], '#000000'],
            ['!=', ['get', 'route_color'], 'black'],
          ],
          [
            'case',
            ['!=', ['slice', ['get', 'route_color'], 0, 1], '#'],
            ['concat', '#', ['get', 'route_color']],
            ['get', 'route_color'],
          ],
          '#ff9966',
        ],
        'text-halo-width': 2,
        'text-halo-blur': 0,
        'text-halo-color': '#ffffff',
        'text-opacity': [
          'interpolate',
          ['linear'],
          ['zoom'],
          12,
          0.8,
          14,
          0.9,
          16,
          1.0,
        ],
        'line-emissive-strength': 1,
      },
    },
  },
  // Route Labels - Metro
  {
    name: 'Metro Labels',
    icon: 'TrainIcon',
    showInLayerSelector: false, // Managed with metro layer
    visible: false,
    type: LayerType.TRANSIT,
    engine: [MapEngine.MAPBOX, MapEngine.MAPLIBRE],
    order: 17,
    groupId: 'Transit',
    configuration: {
      id: 'transitland-metro-labels',
      type: MapboxLayerType.SYMBOL,
      slot: 'top',
      source: {
        id: 'transitland',
        type: SourceType.VECTOR,
        tiles: [buildProxyUrl.value('transitland/routes/{z}/{x}/{y}')],
        maxzoom: 14,
      },
      'source-layer': 'routes',
      filter: ['all', ['==', 'route_type', 1]],
      minzoom: 12,
      layout: {
        'symbol-placement': 'line',
        'text-field': [
          'case',
          ['!=', ['get', 'route_long_name'], ''],
          ['get', 'route_long_name'],
          ['!=', ['get', 'route_short_name'], ''],
          ['get', 'route_short_name'],
          '',
        ],
        'text-font': [
          ['concat', ['config', 'font'], ' Bold'],
          'DIN Pro',
          'Inter',
          'Arial Unicode MS Bold',
        ],
        'text-size': [
          'interpolate',
          ['linear'],
          ['zoom'],
          12,
          10,
          14,
          11,
          16,
          12,
          18,
          13,
        ],
        'text-rotation-alignment': 'map',
        'text-pitch-alignment': 'viewport',
        'symbol-spacing': 400,
        'text-max-angle': 30,
        'text-allow-overlap': false,
        'text-ignore-placement': false,
      },
      paint: {
        'line-emissive-strength': 1,
        'text-color': [
          'case',
          [
            'all',
            ['!=', ['get', 'route_color'], ''],
            ['!=', ['get', 'route_color'], '#000'],
            ['!=', ['get', 'route_color'], '#000000'],
            ['!=', ['get', 'route_color'], 'black'],
          ],
          [
            'case',
            ['!=', ['slice', ['get', 'route_color'], 0, 1], '#'],
            ['concat', '#', ['get', 'route_color']],
            ['get', 'route_color'],
          ],
          '#ff0000',
        ],
        'text-halo-width': 2,
        'text-halo-blur': 0,
        'text-halo-color': '#ffffff',
        'text-opacity': [
          'interpolate',
          ['linear'],
          ['zoom'],
          12,
          0.8,
          14,
          0.9,
          16,
          1.0,
        ],
      },
    },
  },
  // Route Labels - Rail
  {
    name: 'Rail Labels',
    icon: 'TrainIcon',
    showInLayerSelector: false, // Managed with rail layer
    visible: false,
    type: LayerType.TRANSIT,
    engine: [MapEngine.MAPBOX, MapEngine.MAPLIBRE],
    order: 18,
    groupId: 'Transit',
    configuration: {
      id: 'transitland-rail-labels',
      type: MapboxLayerType.SYMBOL,
      slot: 'top',
      source: {
        id: 'transitland',
        type: SourceType.VECTOR,
        tiles: [buildProxyUrl.value('transitland/routes/{z}/{x}/{y}')],
        maxzoom: 14,
      },
      'source-layer': 'routes',
      filter: ['all', ['<', 'route_type', 3]],
      minzoom: 12,
      layout: {
        'symbol-placement': 'line',
        'text-field': [
          'case',
          ['!=', ['get', 'route_long_name'], ''],
          ['get', 'route_long_name'],
          ['!=', ['get', 'route_short_name'], ''],
          ['get', 'route_short_name'],
          '',
        ],
        'text-font': [
          ['concat', ['config', 'font'], ' Bold'],
          'DIN Pro',
          'Inter',
          'Arial Unicode MS Bold',
        ],
        'text-size': [
          'interpolate',
          ['linear'],
          ['zoom'],
          12,
          10,
          14,
          11,
          16,
          12,
          18,
          13,
        ],
        'text-rotation-alignment': 'map',
        'text-pitch-alignment': 'viewport',
        'symbol-spacing': 400,
        'text-max-angle': 30,
        'text-allow-overlap': false,
        'text-ignore-placement': false,
      },
      paint: {
        'text-color': [
          'case',
          [
            'all',
            ['!=', ['get', 'route_color'], ''],
            ['!=', ['get', 'route_color'], '#000'],
            ['!=', ['get', 'route_color'], '#000000'],
            ['!=', ['get', 'route_color'], 'black'],
          ],
          [
            'case',
            ['!=', ['slice', ['get', 'route_color'], 0, 1], '#'],
            ['concat', '#', ['get', 'route_color']],
            ['get', 'route_color'],
          ],
          '#666666',
        ],
        'text-halo-width': 2,
        'text-halo-blur': 0,
        'text-halo-color': '#ffffff',
        'text-opacity': [
          'interpolate',
          ['linear'],
          ['zoom'],
          12,
          0.8,
          14,
          0.9,
          16,
          1.0,
        ],
        'text-emissive-strength': 1,
      },
    },
  },
  // Route Labels - Bus Medium/High
  {
    name: 'Bus Medium Labels',
    icon: 'TrainIcon',
    showInLayerSelector: false, // Managed with bus medium layer
    visible: false,
    type: LayerType.TRANSIT,
    engine: [MapEngine.MAPBOX, MapEngine.MAPLIBRE],
    order: 19,
    groupId: 'Transit',
    configuration: {
      id: 'transitland-bus-medium-labels',
      type: MapboxLayerType.SYMBOL,
      slot: 'top',
      source: {
        id: 'transitland',
        type: SourceType.VECTOR,
        tiles: [buildProxyUrl.value('transitland/routes/{z}/{x}/{y}')],
        maxzoom: 14,
      },
      'source-layer': 'routes',
      filter: [
        'all',
        ['==', 'route_type', 3],
        ['<=', 'headway_secs', 1260],
        ['>', 'headway_secs', 0],
      ],
      minzoom: 13, // Show bus labels at higher zoom since they're more numerous
      layout: {
        'symbol-placement': 'line',
        'text-field': [
          'case',
          ['!=', ['get', 'route_long_name'], ''],
          ['get', 'route_long_name'],
          ['!=', ['get', 'route_short_name'], ''],
          ['get', 'route_short_name'],
          '',
        ],
        'text-font': [
          ['concat', ['config', 'font'], ' Bold'],
          'DIN Pro',
          'Inter',
          'Arial Unicode MS Bold',
        ],
        'text-size': [
          'interpolate',
          ['linear'],
          ['zoom'],
          13,
          9,
          15,
          10,
          17,
          11,
          19,
          12,
        ],
        'text-rotation-alignment': 'map',
        'text-pitch-alignment': 'viewport',
        'symbol-spacing': 300,
        'text-max-angle': 30,
        'text-allow-overlap': false,
        'text-ignore-placement': false,
      },
      paint: {
        'text-color': [
          'case',
          [
            'all',
            ['!=', ['get', 'route_color'], ''],
            ['!=', ['get', 'route_color'], '#000'],
            ['!=', ['get', 'route_color'], '#000000'],
            ['!=', ['get', 'route_color'], 'black'],
          ],
          [
            'case',
            ['!=', ['slice', ['get', 'route_color'], 0, 1], '#'],
            ['concat', '#', ['get', 'route_color']],
            ['get', 'route_color'],
          ],
          '#1c96d6',
        ],
        'text-halo-width': 2,
        'text-halo-blur': 0,
        'text-halo-color': '#ffffff',
        'text-opacity': [
          'interpolate',
          ['linear'],
          ['zoom'],
          13,
          0.7,
          15,
          0.8,
          17,
          0.9,
          19,
          1.0,
        ],
        'text-emissive-strength': 1,
      },
    },
  },
  // Route Labels - Other Routes
  {
    name: 'Other Routes Labels',
    icon: 'TrainIcon',
    showInLayerSelector: false, // Managed with other routes layer
    visible: false,
    type: LayerType.TRANSIT,
    engine: [MapEngine.MAPBOX, MapEngine.MAPLIBRE],
    order: 20,
    groupId: 'Transit',
    configuration: {
      id: 'transitland-other-labels',
      type: MapboxLayerType.SYMBOL,
      slot: 'top',
      source: {
        id: 'transitland',
        type: SourceType.VECTOR,
        tiles: [buildProxyUrl.value('transitland/routes/{z}/{x}/{y}')],
        maxzoom: 14,
      },
      'source-layer': 'routes',
      filter: ['all', ['>', 'route_type', 3]],
      minzoom: 12,
      layout: {
        'symbol-placement': 'line',
        'text-field': [
          'case',
          ['!=', ['get', 'route_long_name'], ''],
          ['get', 'route_long_name'],
          ['!=', ['get', 'route_short_name'], ''],
          ['get', 'route_short_name'],
          '',
        ],
        'text-font': [
          ['concat', ['config', 'font'], ' Bold'],
          'DIN Pro',
          'Inter',
          'Arial Unicode MS Bold',
        ],
        'text-size': [
          'interpolate',
          ['linear'],
          ['zoom'],
          12,
          10,
          14,
          11,
          16,
          12,
          18,
          13,
        ],
        'text-rotation-alignment': 'map',
        'text-pitch-alignment': 'viewport',
        'symbol-spacing': 400,
        'text-max-angle': 30,
        'text-allow-overlap': false,
        'text-ignore-placement': false,
      },
      paint: {
        'text-color': [
          'case',
          [
            'all',
            ['!=', ['get', 'route_color'], ''],
            ['!=', ['get', 'route_color'], '#000'],
            ['!=', ['get', 'route_color'], '#000000'],
            ['!=', ['get', 'route_color'], 'black'],
          ],
          [
            'case',
            ['!=', ['slice', ['get', 'route_color'], 0, 1], '#'],
            ['concat', '#', ['get', 'route_color']],
            ['get', 'route_color'],
          ],
          '#E6A615',
        ],
        'text-halo-width': 2,
        'text-halo-blur': 0,
        'text-halo-color': '#ffffff',
        'text-opacity': [
          'interpolate',
          ['linear'],
          ['zoom'],
          12,
          0.8,
          14,
          0.9,
          16,
          1.0,
        ],
        'text-emissive-strength': 1,
      },
    },
  },
  // Transit Stops
  {
    name: 'Transit Stops',
    icon: 'TrainIcon',
    showInLayerSelector: true,
    visible: false,
    type: LayerType.TRANSIT,
    engine: [MapEngine.MAPBOX, MapEngine.MAPLIBRE],
    order: 21,
    groupId: 'Transit',
    configuration: {
      id: 'transitland-stops',
      type: MapboxLayerType.CIRCLE,
      slot: 'middle',
      source: {
        id: 'transitland-stops',
        type: SourceType.VECTOR,
        tiles: [buildProxyUrl.value('transitland/stops/{z}/{x}/{y}')],
        maxzoom: 14,
      },
      'source-layer': 'stops',
      minzoom: 12, // Only show stops at higher zoom levels
      layout: {},
      paint: {
        'circle-radius': [
          'interpolate',
          ['linear'],
          ['zoom'],
          12,
          2,
          14,
          3,
          16,
          4,
          18,
          5,
        ],
        'circle-color': '#007cbf', // Transitland blue for stops
        'circle-stroke-width': [
          'interpolate',
          ['linear'],
          ['zoom'],
          12,
          1,
          16,
          2,
        ],
        'circle-stroke-color': '#ffffff',
        'circle-opacity': 0.9,
        'circle-stroke-opacity': 1.0,
        'circle-emissive-strength': 1,
      },
    },
  },
  // Transit Stop Labels
  {
    name: 'Transit Stop Labels',
    icon: 'TrainIcon',
    showInLayerSelector: false, // Managed with stops layer
    visible: false,
    type: LayerType.TRANSIT,
    engine: [MapEngine.MAPBOX, MapEngine.MAPLIBRE],
    order: 22,
    groupId: 'Transit',
    configuration: {
      id: 'transitland-stops-labels',
      type: MapboxLayerType.SYMBOL,
      slot: 'top',
      source: {
        id: 'transitland-stops',
        type: SourceType.VECTOR,
        tiles: [buildProxyUrl.value('transitland/stops/{z}/{x}/{y}')],
        maxzoom: 14,
      },
      'source-layer': 'stops',
      minzoom: 14, // Only show labels at high zoom
      filter: ['has', 'stop_name'],
      layout: {
        'text-field': ['get', 'stop_name'],
        'text-font': [
          ['concat', ['config', 'font'], ' Medium'],
          'DIN Pro',
          'Inter',
          'Arial Unicode MS Bold',
        ],
        'text-size': [
          'interpolate',
          ['linear'],
          ['zoom'],
          14,
          9,
          16,
          10,
          18,
          11,
        ],
        'text-offset': [1, 0],
        'text-anchor': 'left',
        'text-allow-overlap': false,
        'text-ignore-placement': false,
        'symbol-sort-key': 100,
      },
      paint: {
        'text-color': [
          'interpolate',
          ['linear'],
          ['measure-light', 'brightness'],
          0.25,
          'hsl(0, 0%, 95%)',
          0.3,
          'hsl(0, 0%, 15%)',
        ],
        'text-halo-width': 1.5,
        'text-halo-blur': 0,
        'text-halo-color': [
          'interpolate',
          ['linear'],
          ['measure-light', 'brightness'],
          0.25,
          'hsl(0, 0%, 5%)',
          0.3,
          'hsl(0, 0%, 100%)',
        ],
        'text-emissive-strength': 1,
      },
    },
  },
])
