import {
  LayerType,
  MapEngine,
  MapboxLayerType,
  SourceType,
} from '@/types/map.types'
import type { Layer } from '@/types/map.types'
import { buildProxyUrl } from './helpers'
import { computed } from 'vue'

// Database-persisted layer templates that users can add to their account
export const USER_LAYER_TEMPLATES = computed(
  (): Omit<Layer, 'id' | 'userId' | 'createdAt' | 'updatedAt'>[] => [
  // Loom Transit layers
  {
    name: 'Loom Light Rail',
    icon: 'TrainIcon',
    showInLayerSelector: true,
    visible: false,
    type: LayerType.CUSTOM,
    engine: [MapEngine.MAPBOX, MapEngine.MAPLIBRE],
    groupId: 'Loom Transit',
    order: 5,
    configuration: {
      id: 'loom-light-rail',
      type: MapboxLayerType.LINE,
      slot: 'middle',
      source: {
        id: 'loom-light-rail',
        type: SourceType.VECTOR,
        tiles: [buildProxyUrl.value('loom/subway-lightrail/geo/{z}/{x}/{y}')],
        maxzoom: 17,
      },
      'source-layer': 'lines',
      paint: {
        'line-color': ['concat', '#', ['get', 'color']],
        'line-width': 5,
        'line-opacity': 1,
        'line-emissive-strength': 1,
        'line-occlusion-opacity': 0.15,
      },
      layout: {
        'line-cap': 'round',
        'line-join': 'round',
      },
    },
  },
  {
    name: 'Loom Tram',
    icon: 'TrainIcon',
    showInLayerSelector: true,
    visible: false,
    type: LayerType.CUSTOM,
    engine: [MapEngine.MAPBOX, MapEngine.MAPLIBRE],
    groupId: 'Loom Transit',
    order: 6,
    configuration: {
      id: 'loom-tram',
      type: MapboxLayerType.LINE,
      slot: 'middle',
      source: {
        id: 'loom-tram',
        type: SourceType.VECTOR,
        tiles: [buildProxyUrl.value('loom/tram/geo/{z}/{x}/{y}')],
        maxzoom: 17,
      },
      'source-layer': 'lines',
      paint: {
        'line-color': ['concat', '#', ['get', 'color']],
        'line-width': 5,
        'line-opacity': 1,
        'line-emissive-strength': 1,
        'line-occlusion-opacity': 0.15,
      },
      layout: {
        'line-cap': 'round',
        'line-join': 'round',
      },
    },
  },
  {
    name: 'Loom Rail (Commuter)',
    icon: 'TrainIcon',
    showInLayerSelector: true,
    visible: false,
    type: LayerType.CUSTOM,
    engine: [MapEngine.MAPBOX, MapEngine.MAPLIBRE],
    groupId: 'Loom Transit',
    order: 7,
    configuration: {
      id: 'loom-rail-commuter',
      type: MapboxLayerType.LINE,
      slot: 'middle',
      source: {
        id: 'loom-rail-commuter',
        type: SourceType.VECTOR,
        tiles: [buildProxyUrl.value('loom/rail-commuter/geo/{z}/{x}/{y}')],
        maxzoom: 17,
      },
      'source-layer': 'lines',
      paint: {
        'line-color': ['concat', '#', ['get', 'color']],
        'line-width': 5,
        'line-opacity': 1,
        'line-emissive-strength': 1,
        'line-occlusion-opacity': 0.15,
      },
      layout: {
        'line-cap': 'round',
        'line-join': 'round',
      },
    },
  },
  {
    name: 'Loom Rail (Long Distance)',
    icon: 'TrainIcon',
    showInLayerSelector: true,
    visible: false,
    type: LayerType.CUSTOM,
    engine: [MapEngine.MAPBOX, MapEngine.MAPLIBRE],
    groupId: 'Loom Transit',
    order: 8,
    configuration: {
      id: 'loom-rail',
      type: MapboxLayerType.LINE,
      slot: 'middle',
      source: {
        id: 'loom-rail',
        type: SourceType.VECTOR,
        tiles: [buildProxyUrl.value('loom/rail/geo/{z}/{x}/{y}')],
        maxzoom: 17,
      },
      'source-layer': 'lines',
      paint: {
        'line-color': ['concat', '#', ['get', 'color']],
        'line-width': 5,
        'line-opacity': 1,
        'line-emissive-strength': 1,
        'line-occlusion-opacity': 0.15,
      },
      layout: {
        'line-cap': 'round',
        'line-join': 'round',
      },
    },
  },

  // Mapbox-specific layers
  {
    name: 'Mapbox traffic',
    icon: 'CarFrontIcon',
    showInLayerSelector: true,
    visible: false,
    type: LayerType.CUSTOM,
    engine: [MapEngine.MAPBOX],
    order: 10,
    groupId: null,
    configuration: {
      id: 'traffic',
      type: MapboxLayerType.LINE,
      slot: 'middle',
      source: {
        id: 'traffic',
        type: SourceType.VECTOR,
        url: 'mapbox://mapbox.mapbox-traffic-v1',
        attribution: 'Mapbox',
      },
      'source-layer': 'traffic',
      layout: {
        'line-cap': 'round',
        'line-join': 'round',
      },
      paint: {
        'line-width': ['interpolate', ['linear'], ['zoom'], 14, 2, 20, 7],
        'line-offset': ['interpolate', ['linear'], ['zoom'], 14, 0, 20, 2],
        'line-color': [
          'match',
          ['get', 'congestion'],
          'low',
          '#1A9641',
          'moderate',
          '#EED322',
          'heavy',
          '#E6B71E',
          'severe',
          '#DA3838',
          '#000000',
        ],
        'line-opacity': 0.8,
        'line-occlusion-opacity': 0.15,
        'line-emissive-strength': 1,
      },
    },
  },
  {
    name: 'Hillshade',
    icon: 'MountainSnowIcon',
    showInLayerSelector: true,
    visible: false,
    type: LayerType.CUSTOM,
    engine: [MapEngine.MAPBOX],
    groupId: 'Terrain',
    order: 11,
    configuration: {
      id: 'hillshade',
      type: MapboxLayerType.HILLSHADE,
      source: {
        id: 'terrain-rgb',
        type: SourceType.RASTER_DEM,
        url: 'mapbox://mapbox.mapbox-terrain-dem-v1',
      },
      paint: {
        'hillshade-shadow-color': '#0f172a',
        'hillshade-highlight-color': '#fef3c7',
        'hillshade-accent-color': '#fcd34d',
        'hillshade-illumination-direction': 315,
        'hillshade-exaggeration': 1,
      },
    },
  },
  {
    name: 'Contours',
    icon: 'MountainSnowIcon',
    showInLayerSelector: true,
    visible: false,
    type: LayerType.CUSTOM,
    engine: [MapEngine.MAPBOX],
    groupId: 'Terrain',
    order: 12,
    configuration: {
      id: 'contours',
      type: MapboxLayerType.LINE,
      source: {
        id: 'contours',
        type: SourceType.VECTOR,
        url: 'mapbox://mapbox.mapbox-terrain-v2',
      },
      'source-layer': 'contour',
      paint: {
        'line-color': '#334155',
        'line-width': ['interpolate', ['linear'], ['zoom'], 11, 0.5, 16, 1],
        'line-opacity': [
          'interpolate',
          ['linear'],
          ['zoom'],
          11,
          0.5,
          16,
          0.8,
        ],
      },
      layout: {
        'line-join': 'round',
      },
    },
  },
  {
    name: 'Contour Labels',
    icon: 'MountainSnowIcon',
    showInLayerSelector: true,
    visible: false,
    type: LayerType.CUSTOM,
    engine: [MapEngine.MAPBOX],
    groupId: 'Terrain',
    order: 13,
    configuration: {
      id: 'contour-labels',
      type: MapboxLayerType.SYMBOL,
      source: {
        id: 'contours',
        type: SourceType.VECTOR,
        url: 'mapbox://mapbox.mapbox-terrain-v2',
      },
      'source-layer': 'contour',
      paint: {
        'text-color': '#334155',
        'text-halo-color': '#ffffff',
        'text-halo-width': 1,
      },
      layout: {
        'symbol-placement': 'line',
        'text-field': ['concat', ['get', 'ele'], 'm'],
        'text-font': ['DIN Pro Medium', 'Arial Unicode MS Regular'],
        'text-size': 10,
        'text-letter-spacing': 0.1,
        'text-max-angle': 30,
        'text-padding': 5,
      },
    },
  },
])
