import { DefaultLayerGroupTemplate } from '../../types/layers.types'

export const DEFAULT_LAYER_GROUPS: DefaultLayerGroupTemplate[] = [
  {
    templateId: 'default:group:cycling',
    name: 'Cycling',
    icon: 'BikeIcon',
    showInLayerSelector: true,
    visible: false,
    order: 0,
    parentGroupId: null,
  },
  // Cycling subgroups
  {
    templateId: 'default:group:cycling:cycleways',
    name: 'Cycleways',
    icon: 'BikeIcon',
    showInLayerSelector: true,
    visible: false,
    order: 0,
    parentGroupId: 'default:group:cycling',
    integrationId: 'barrelman',
  },
  {
    templateId: 'default:group:cycling:cycle-tracks',
    name: 'Cycle Tracks',
    icon: 'BikeIcon',
    showInLayerSelector: true,
    visible: false,
    order: 1,
    parentGroupId: 'default:group:cycling',
    integrationId: 'barrelman',
  },
  {
    templateId: 'default:group:cycling:bike-lanes',
    name: 'Bike Lanes',
    icon: 'BikeIcon',
    showInLayerSelector: true,
    visible: false,
    order: 2,
    parentGroupId: 'default:group:cycling',
    integrationId: 'barrelman',
  },
  {
    templateId: 'default:group:cycling:shared-lanes',
    name: 'Shared Lanes',
    icon: 'BikeIcon',
    showInLayerSelector: true,
    visible: false,
    order: 3,
    parentGroupId: 'default:group:cycling',
    integrationId: 'barrelman',
  },
  {
    templateId: 'default:group:cycling:bicycle-paths',
    name: 'Bicycle Paths',
    icon: 'BikeIcon',
    showInLayerSelector: true,
    visible: false,
    order: 4,
    parentGroupId: 'default:group:cycling',
    integrationId: 'barrelman',
  },
  {
    templateId: 'default:group:cycling:bicycle-roads',
    name: 'Bicycle Roads',
    icon: 'BikeIcon',
    showInLayerSelector: true,
    visible: false,
    order: 5,
    parentGroupId: 'default:group:cycling',
    integrationId: 'barrelman',
  },
  {
    templateId: 'default:group:cycling:bicycle-permitted',
    name: 'Bicycle Permitted',
    icon: 'BikeIcon',
    showInLayerSelector: true,
    visible: false,
    order: 6,
    parentGroupId: 'default:group:cycling',
    integrationId: 'barrelman',
  },
  {
    templateId: 'default:group:cycling:proposed-bikeways',
    name: 'Proposed Bikeways',
    icon: 'BikeIcon',
    showInLayerSelector: true,
    visible: false,
    order: 7,
    parentGroupId: 'default:group:cycling',
    integrationId: 'barrelman',
  },
  {
    templateId: 'default:group:cycling:bike-routes',
    name: 'Bike Routes',
    icon: 'BikeIcon',
    showInLayerSelector: true,
    visible: false,
    order: 8,
    parentGroupId: 'default:group:cycling',
    integrationId: 'barrelman',
  },
  {
    templateId: 'default:group:mapillary',
    name: 'Mapillary',
    icon: 'CameraIcon',
    showInLayerSelector: true,
    visible: false,
    order: 1,
    parentGroupId: null,
  },
  {
    templateId: 'default:group:transit',
    name: 'Transit',
    icon: 'TrainIcon',
    showInLayerSelector: true,
    visible: false,
    fadeBasemap: true,
    order: 2,
    parentGroupId: null,
  },
  {
    templateId: 'default:group:loom-transit',
    name: 'Loom Transit',
    icon: 'TrainIcon',
    showInLayerSelector: true,
    visible: false,
    order: 3,
    parentGroupId: null,
    integrationId: 'loom',
  },
  {
    templateId: 'default:group:terrain',
    name: 'Terrain',
    icon: 'MountainSnowIcon',
    showInLayerSelector: true,
    visible: false,
    order: 4,
    parentGroupId: null,
  },
]
