import { DefaultLayerGroupTemplate } from '../../types/layers.types'

export const DEFAULT_LAYER_GROUPS: DefaultLayerGroupTemplate[] = [
  {
    templateId: 'default:group:cycling',
    description:
      'Bike lanes, cycle tracks and signed routes from OpenStreetMap.',
    name: 'Cycling',
    icon: 'BikeIcon',
    showInLayerSelector: true,
    visible: false,
    order: 0,
    parentGroupId: null,
  },
  // Cycling subgroups
  {
    templateId: 'default:group:cycling:cycleways',
    name: 'Cycleways',
    icon: 'BikeIcon',
    showInLayerSelector: true,
    visible: false,
    order: 0,
    parentGroupId: 'default:group:cycling',
    integrationId: 'barrelman',
  },
  {
    templateId: 'default:group:cycling:cycle-tracks',
    name: 'Cycle Tracks',
    icon: 'BikeIcon',
    showInLayerSelector: true,
    visible: false,
    order: 1,
    parentGroupId: 'default:group:cycling',
    integrationId: 'barrelman',
  },
  {
    templateId: 'default:group:cycling:bike-lanes',
    name: 'Bike Lanes',
    icon: 'BikeIcon',
    showInLayerSelector: true,
    visible: false,
    order: 2,
    parentGroupId: 'default:group:cycling',
    integrationId: 'barrelman',
  },
  {
    templateId: 'default:group:cycling:shared-lanes',
    name: 'Shared Lanes',
    icon: 'BikeIcon',
    showInLayerSelector: true,
    visible: false,
    order: 3,
    parentGroupId: 'default:group:cycling',
    integrationId: 'barrelman',
  },
  {
    templateId: 'default:group:cycling:bicycle-paths',
    name: 'Bicycle Paths',
    icon: 'BikeIcon',
    showInLayerSelector: true,
    visible: false,
    order: 4,
    parentGroupId: 'default:group:cycling',
    integrationId: 'barrelman',
  },
  {
    templateId: 'default:group:cycling:bicycle-roads',
    name: 'Bicycle Roads',
    icon: 'BikeIcon',
    showInLayerSelector: true,
    visible: false,
    order: 5,
    parentGroupId: 'default:group:cycling',
    integrationId: 'barrelman',
  },
  {
    templateId: 'default:group:cycling:bicycle-permitted',
    name: 'Bicycle Permitted',
    icon: 'BikeIcon',
    showInLayerSelector: true,
    visible: false,
    order: 6,
    parentGroupId: 'default:group:cycling',
    integrationId: 'barrelman',
  },
  {
    templateId: 'default:group:cycling:proposed-bikeways',
    name: 'Proposed Bikeways',
    icon: 'BikeIcon',
    showInLayerSelector: true,
    visible: false,
    order: 7,
    parentGroupId: 'default:group:cycling',
    integrationId: 'barrelman',
  },
  {
    templateId: 'default:group:cycling:bike-routes',
    name: 'Bike Routes',
    icon: 'BikeIcon',
    showInLayerSelector: true,
    visible: false,
    order: 8,
    parentGroupId: 'default:group:cycling',
    integrationId: 'barrelman',
  },
  {
    templateId: 'default:group:mapillary',
    description:
      'Street-level photo coverage and sequences from Mapillary.',
    name: 'Street imagery',
    icon: 'CameraIcon',
    showInLayerSelector: true,
    visible: false,
    order: 1,
    parentGroupId: null,
  },
  {
    templateId: 'default:group:transit',
    description:
      'Rail, tram and bus lines with clickable stops and live departures.',
    name: 'Transit',
    icon: 'TrainIcon',
    showInLayerSelector: true,
    visible: false,
    fadeBasemap: true,
    order: 2,
    parentGroupId: null,
  },
  {
    templateId: 'default:group:loom-transit',
    description:
      'Schematic transit lines rendered by a Loom server.',
    name: 'Loom Transit',
    icon: 'TrainIcon',
    showInLayerSelector: true,
    visible: false,
    order: 3,
    parentGroupId: null,
    integrationId: 'loom',
  },
  {
    templateId: 'default:group:terrain',
    description: 'Hillshading and elevation contours over the basemap.',
    installedByDefault: false,
    name: 'Terrain',
    icon: 'MountainSnowIcon',
    showInLayerSelector: true,
    visible: false,
    order: 4,
    parentGroupId: null,
  },
  {
    templateId: 'default:group:daynight',
    description: 'A shaded overlay tracking the day/night terminator.',
    name: 'Day & Night',
    icon: 'SunMoonIcon',
    showInLayerSelector: true,
    visible: false,
    order: 5,
    parentGroupId: null,
  },
  {
    templateId: 'default:group:timezone',
    description: 'Time zone boundaries with their current local time.',
    installedByDefault: false,
    name: 'Time Zones',
    icon: 'ClockIcon',
    showInLayerSelector: true,
    visible: false,
    order: 6,
    parentGroupId: null,
  },
  {
    templateId: 'default:group:air-quality',
    description: 'A global PM2.5 surface from Copernicus CAMS.',
    installedByDefault: false,
    name: 'Air Quality',
    icon: 'WindIcon',
    showInLayerSelector: true,
    visible: false,
    order: 7,
    parentGroupId: null,
  },
  {
    templateId: 'default:group:wildfires',
    description: 'Active fire hotspots, perimeters and smoke plumes.',
    installedByDefault: false,
    name: 'Wildfires',
    icon: 'FlameIcon',
    showInLayerSelector: true,
    visible: false,
    order: 8,
    parentGroupId: null,
  },
]
