import { DefaultLayerTemplate } from '../../types/layers.types'
import { LayerType } from '../../schema/layers.schema'

export const MAPILLARY_LAYER_TEMPLATES: DefaultLayerTemplate[] = [
  {
    templateId: 'default:mapillary-overview',
    name: 'Mapillary Overview',
    type: LayerType.STREET_VIEW,
    engine: ['mapbox', 'maplibre'],
    showInLayerSelector: true,
    visible: false,
    icon: 'CameraIcon',
    order: 0,
    groupId: 'default:group:mapillary',
    isSubLayer: false,
    integrationId: 'mapillary',
    configuration: {
      id: 'mapillary-overview',
      type: 'circle',
      slot: 'middle',
      source: {
        id: 'mapillary-overview',
        type: 'vector',
        tiles: ['{PROXY_URL}/mapillary/mly1_computed_public/2/{z}/{x}/{y}'],
        minzoom: 0,
        maxzoom: 5,
      },
      'source-layer': 'images',
      paint: {
        'circle-color': '#04CB63',
        'circle-radius': 4,
        'circle-opacity': 1,
        'circle-stroke-color': '#04CB63',
        'circle-stroke-width': 1.5,
        'circle-stroke-opacity': 0.7,
        'circle-emissive-strength': 1,
      },
    },
  },
  {
    templateId: 'default:mapillary-sequence',
    name: 'Mapillary Sequences',
    type: LayerType.STREET_VIEW,
    engine: ['mapbox', 'maplibre'],
    showInLayerSelector: true,
    visible: false,
    icon: 'CameraIcon',
    order: 1,
    groupId: 'default:group:mapillary',
    isSubLayer: false,
    integrationId: 'mapillary',
    configuration: {
      id: 'mapillary-sequence',
      type: 'line',
      slot: 'middle',
      source: {
        id: 'mapillary-sequence',
        type: 'vector',
        tiles: ['{PROXY_URL}/mapillary/mly1_computed_public/2/{z}/{x}/{y}'],
        minzoom: 6,
        maxzoom: 14,
      },
      'source-layer': 'sequence',
      paint: {
        'line-color': '#04CB63',
        'line-opacity': [
          'interpolate', ['linear'], ['zoom'],
          6, 0, 14, 1, 22, 0.5,
        ],
        'line-width': [
          'interpolate', ['linear'], ['zoom'],
          6, 0, 7, 1, 14, 2,
        ],
        'line-emissive-strength': 1,
      },
      layout: {
        'line-cap': 'round',
        'line-join': 'round',
      },
    },
  },
  {
    templateId: 'default:mapillary-image',
    name: 'Mapillary Images',
    type: LayerType.STREET_VIEW,
    engine: ['mapbox', 'maplibre'],
    showInLayerSelector: true,
    visible: false,
    icon: 'CameraIcon',
    order: 2,
    groupId: 'default:group:mapillary',
    isSubLayer: false,
    integrationId: 'mapillary',
    configuration: {
      id: 'mapillary-image',
      type: 'circle',
      slot: 'middle',
      source: {
        id: 'mapillary-image',
        type: 'vector',
        tiles: ['{PROXY_URL}/mapillary/mly1_computed_public/2/{z}/{x}/{y}'],
        minzoom: 6,
        maxzoom: 14,
      },
      'source-layer': 'image',
      paint: {
        'circle-color': '#04CB63',
        'circle-radius': [
          'interpolate', ['linear'], ['zoom'],
          14, 0, 16, 3, 22, 6,
        ],
        'circle-opacity': 1,
        'circle-stroke-color': '#04CB63',
        'circle-stroke-width': [
          'interpolate', ['linear'], ['zoom'],
          14, 0, 16, 2,
        ],
        'circle-stroke-opacity': 0.7,
        'circle-emissive-strength': 1,
      },
    },
  },
]
