import { DefaultLayerTemplate } from '../../types/layers.types'
import { LayerType } from '../../schema/layers.schema'

export const TIMEZONE_LAYER_TEMPLATES: DefaultLayerTemplate[] = [
  {
    templateId: 'default:timezone-fill',
    name: 'Timezone Fill',
    type: LayerType.CUSTOM,
    engine: ['mapbox', 'maplibre'],
    icon: 'ClockIcon',
    showInLayerSelector: false,
    visible: false,
    order: 0,
    groupId: 'default:group:timezone',
    isSubLayer: true,
    configuration: {
      id: 'timezone-fill',
      type: 'fill',
      source: {
        id: 'timezones',
        type: 'geojson',
        data: '{SERVER_URL}/data/timezones.geojson',
        generateId: true,
      },
      paint: {
        'fill-color': [
          'case',
          ['==', ['%', ['id'], 2], 0],
          'rgba(0, 0, 0, 0.0)',
          'rgba(0, 0, 0, 1.0)',
        ],
        'fill-opacity': [
          'interpolate',
          ['linear'],
          ['zoom'],
          1, 0.02,
          8, 0.02,
          10, 0,
        ],
        'fill-emissive-strength': 0.5,
      },
    },
  },
  {
    templateId: 'default:timezone-boundaries',
    name: 'Timezone Boundaries',
    type: LayerType.CUSTOM,
    engine: ['mapbox', 'maplibre'],
    icon: 'ClockIcon',
    showInLayerSelector: false,
    visible: false,
    order: 1,
    groupId: 'default:group:timezone',
    isSubLayer: true,
    configuration: {
      id: 'timezone-boundaries',
      type: 'line',
      source: {
        id: 'timezones',
        type: 'geojson',
        data: '{SERVER_URL}/data/timezones.geojson',
      },
      paint: {
        'line-color': [
          'interpolate',
          ['linear'],
          ['measure-light', 'brightness'],
          0.25,
          'rgba(148, 163, 184, 0.5)',
          0.3,
          'rgba(100, 116, 139, 0.4)',
        ],
        'line-width': [
          'interpolate',
          ['linear'],
          ['zoom'],
          1, 0.5,
          4, 1,
          8, 1.5,
        ],
        'line-dasharray': [4, 2],
        'line-emissive-strength': 0.6,
      },
    },
  },
  {
    templateId: 'default:timezone-labels',
    name: 'Timezone Labels',
    type: LayerType.CUSTOM,
    engine: ['mapbox', 'maplibre'],
    icon: 'ClockIcon',
    showInLayerSelector: false,
    visible: false,
    order: 2,
    groupId: 'default:group:timezone',
    isSubLayer: true,
    configuration: {
      id: 'timezone-labels',
      type: 'symbol',
      source: {
        id: 'timezones',
        type: 'geojson',
        data: '{SERVER_URL}/data/timezones.geojson',
      },
      minzoom: 0,
      paint: {
        'text-color': [
          'interpolate',
          ['linear'],
          ['measure-light', 'brightness'],
          0.25,
          'rgba(203, 213, 225, 0.8)',
          0.3,
          'rgba(71, 85, 105, 0.8)',
        ],
        'text-halo-color': [
          'interpolate',
          ['linear'],
          ['measure-light', 'brightness'],
          0.25,
          'rgba(15, 23, 42, 0.6)',
          0.3,
          'rgba(255, 255, 255, 0.6)',
        ],
        'text-halo-width': 1.5,
        'text-emissive-strength': 0.7,
      },
      layout: {
        'symbol-placement': 'line',
        'text-field': ['get', 'tzid'],
        'text-font': ['DIN Pro Medium', 'Arial Unicode MS Regular'],
        'text-size': [
          'interpolate',
          ['linear'],
          ['zoom'],
          0, 7,
          3, 9,
          6, 10,
          10, 12,
        ],
        'text-letter-spacing': 0.05,
        'text-offset': [0, 0.8],
        'symbol-spacing': 250,
        'text-rotation-alignment': 'map',
        'text-allow-overlap': false,
      },
    },
  },
]
