import { DefaultLayerTemplate } from '../../types/layers.types'

export const USER_LAYER_TEMPLATES: DefaultLayerTemplate[] = [
  // Loom Transit layers
  {
    templateId: 'default:loom-light-rail',
    name: 'Loom Light Rail',
    type: 'custom',
    engine: ['mapbox', 'maplibre'],
    showInLayerSelector: true,
    visible: false,
    icon: 'TrainIcon',
    order: 5,
    groupId: 'default:group:loom-transit',
    isSubLayer: false,
    integrationId: 'loom',
    configuration: {
      id: 'loom-light-rail',
      type: 'line',
      slot: 'middle',
      source: {
        id: 'loom-light-rail',
        type: 'vector',
        tiles: ['{PROXY_URL}/loom/subway-lightrail/geo/{z}/{x}/{y}'],
        maxzoom: 17,
      },
      'source-layer': 'lines',
      paint: {
        'line-color': ['concat', '#', ['get', 'color']],
        'line-width': 5,
        'line-opacity': 1,
        'line-emissive-strength': 1,
        'line-occlusion-opacity': 0.15,
      },
      layout: {
        'line-cap': 'round',
        'line-join': 'round',
      },
    },
  },
  {
    templateId: 'default:loom-tram',
    name: 'Loom Tram',
    type: 'custom',
    engine: ['mapbox', 'maplibre'],
    showInLayerSelector: true,
    visible: false,
    icon: 'TrainIcon',
    order: 6,
    groupId: 'default:group:loom-transit',
    isSubLayer: false,
    integrationId: 'loom',
    configuration: {
      id: 'loom-tram',
      type: 'line',
      slot: 'middle',
      source: {
        id: 'loom-tram',
        type: 'vector',
        tiles: ['{PROXY_URL}/loom/tram/geo/{z}/{x}/{y}'],
        maxzoom: 17,
      },
      'source-layer': 'lines',
      paint: {
        'line-color': ['concat', '#', ['get', 'color']],
        'line-width': 5,
        'line-opacity': 1,
        'line-emissive-strength': 1,
        'line-occlusion-opacity': 0.15,
      },
      layout: {
        'line-cap': 'round',
        'line-join': 'round',
      },
    },
  },
  {
    templateId: 'default:loom-rail-commuter',
    name: 'Loom Rail (Commuter)',
    type: 'custom',
    engine: ['mapbox', 'maplibre'],
    showInLayerSelector: true,
    visible: false,
    icon: 'TrainIcon',
    order: 7,
    groupId: 'default:group:loom-transit',
    isSubLayer: false,
    integrationId: 'loom',
    configuration: {
      id: 'loom-rail-commuter',
      type: 'line',
      slot: 'middle',
      source: {
        id: 'loom-rail-commuter',
        type: 'vector',
        tiles: ['{PROXY_URL}/loom/rail-commuter/geo/{z}/{x}/{y}'],
        maxzoom: 17,
      },
      'source-layer': 'lines',
      paint: {
        'line-color': ['concat', '#', ['get', 'color']],
        'line-width': 5,
        'line-opacity': 1,
        'line-emissive-strength': 1,
        'line-occlusion-opacity': 0.15,
      },
      layout: {
        'line-cap': 'round',
        'line-join': 'round',
      },
    },
  },
  {
    templateId: 'default:loom-rail',
    name: 'Loom Rail (Long Distance)',
    type: 'custom',
    engine: ['mapbox', 'maplibre'],
    showInLayerSelector: true,
    visible: false,
    icon: 'TrainIcon',
    order: 8,
    groupId: 'default:group:loom-transit',
    isSubLayer: false,
    integrationId: 'loom',
    configuration: {
      id: 'loom-rail',
      type: 'line',
      slot: 'middle',
      source: {
        id: 'loom-rail',
        type: 'vector',
        tiles: ['{PROXY_URL}/loom/rail/geo/{z}/{x}/{y}'],
        maxzoom: 17,
      },
      'source-layer': 'lines',
      paint: {
        'line-color': ['concat', '#', ['get', 'color']],
        'line-width': 5,
        'line-opacity': 1,
        'line-emissive-strength': 1,
        'line-occlusion-opacity': 0.15,
      },
      layout: {
        'line-cap': 'round',
        'line-join': 'round',
      },
    },
  },

  // Mapbox-specific layers
  {
    templateId: 'default:traffic',
    name: 'Mapbox traffic',
    type: 'custom',
    engine: ['mapbox'],
    showInLayerSelector: true,
    visible: false,
    icon: 'CarFrontIcon',
    order: 10,
    groupId: null,
    isSubLayer: false,
    integrationId: null,
    configuration: {
      id: 'traffic',
      type: 'line',
      slot: 'middle',
      source: {
        id: 'traffic',
        type: 'vector',
        url: 'mapbox://mapbox.mapbox-traffic-v1',
        attribution: 'Mapbox',
      },
      'source-layer': 'traffic',
      layout: {
        'line-cap': 'round',
        'line-join': 'round',
      },
      paint: {
        'line-width': ['interpolate', ['linear'], ['zoom'], 14, 2, 20, 7],
        'line-offset': ['interpolate', ['linear'], ['zoom'], 14, 0, 20, 2],
        'line-color': [
          'match',
          ['get', 'congestion'],
          'low', '#1A9641',
          'moderate', '#EED322',
          'heavy', '#E6B71E',
          'severe', '#DA3838',
          '#000000',
        ],
        'line-opacity': 0.8,
        'line-occlusion-opacity': 0.15,
        'line-emissive-strength': 1,
      },
    },
  },
  {
    templateId: 'default:hillshade',
    name: 'Hillshade',
    type: 'custom',
    engine: ['mapbox'],
    showInLayerSelector: true,
    visible: false,
    icon: 'MountainSnowIcon',
    order: 11,
    groupId: 'default:group:terrain',
    isSubLayer: false,
    integrationId: null,
    configuration: {
      id: 'hillshade',
      type: 'hillshade',
      source: {
        id: 'terrain-rgb',
        type: 'raster-dem',
        url: 'mapbox://mapbox.mapbox-terrain-dem-v1',
      },
      paint: {
        'hillshade-shadow-color': '#0f172a',
        'hillshade-highlight-color': '#fef3c7',
        'hillshade-accent-color': '#fcd34d',
        'hillshade-illumination-direction': 315,
        'hillshade-exaggeration': 1,
      },
    },
  },
  {
    templateId: 'default:contours',
    name: 'Contours',
    type: 'custom',
    engine: ['mapbox'],
    showInLayerSelector: true,
    visible: false,
    icon: 'MountainSnowIcon',
    order: 12,
    groupId: 'default:group:terrain',
    isSubLayer: false,
    integrationId: null,
    configuration: {
      id: 'contours',
      type: 'line',
      source: {
        id: 'contours',
        type: 'vector',
        url: 'mapbox://mapbox.mapbox-terrain-v2',
      },
      'source-layer': 'contour',
      paint: {
        'line-color': '#334155',
        'line-width': ['interpolate', ['linear'], ['zoom'], 11, 0.5, 16, 1],
        'line-opacity': [
          'interpolate', ['linear'], ['zoom'],
          11, 0.5, 16, 0.8,
        ],
      },
      layout: {
        'line-join': 'round',
      },
    },
  },
  {
    templateId: 'default:contour-labels',
    name: 'Contour Labels',
    type: 'custom',
    engine: ['mapbox'],
    showInLayerSelector: true,
    visible: false,
    icon: 'MountainSnowIcon',
    order: 13,
    groupId: 'default:group:terrain',
    isSubLayer: false,
    integrationId: null,
    configuration: {
      id: 'contour-labels',
      type: 'symbol',
      source: {
        id: 'contours',
        type: 'vector',
        url: 'mapbox://mapbox.mapbox-terrain-v2',
      },
      'source-layer': 'contour',
      paint: {
        'text-color': '#334155',
        'text-halo-color': '#ffffff',
        'text-halo-width': 1,
      },
      layout: {
        'symbol-placement': 'line',
        'text-field': ['concat', ['get', 'ele'], 'm'],
        'text-font': ['DIN Pro Medium', 'Arial Unicode MS Regular'],
        'text-size': 10,
        'text-letter-spacing': 0.1,
        'text-max-angle': 30,
        'text-padding': 5,
      },
    },
  },
]
