export const appName = 'Parchment Maps'

export { default as healthCheck } from './health-check.controller'
export { default as auth } from './auth.controller'
export { default as user } from './user.controller'
export { default as directions } from './directions.controller'
export { default as place } from './place.controller'
export { default as proxy } from './proxy.controller'
export { default as library } from './library'
export { default as integrations } from './integration.controller'
export { default as search } from './search.controller'
export { default as geocoding } from './geocoding.controller'
export { default as federation } from './federation.controller'
export { default as friends } from './friends.controller'
export { default as sharing } from './sharing.controller'
export { default as location } from './location.controller'
export { default as weather } from './weather.controller'
export { default as osmOAuth } from './osm-oauth.controller'
export { default as notes } from './notes.controller'
export { default as personalBlob } from './personal-blob.controller'
export { default as wrappedMasterKeys } from './wrapped-master-keys.controller'
export { default as deviceTransfer } from './device-transfer.controller'
export { default as deviceWrapSecrets } from './device-wrap-secrets.controller'
export { default as publicController } from './public.controller'
export { default as realtime } from './realtime.controller'
