export const appName = 'Parchment Maps'

export { default as auth } from './auth.controller'
export { default as user } from './user.controller'
export { default as directions } from './directions.controller'
export { default as place } from './place.controller'
export { default as proxy } from './proxy.controller'
export { default as library } from './library'
export { default as integrations } from './integration.controller'
export { default as search } from './search.controller'
