# TODO: Verify this is building and running correctly

FROM oven/bun:latest as builder
WORKDIR /app
COPY package.json bun.lockb ./
RUN bun install
COPY . .
RUN bun run build

FROM oven/bun:latest
WORKDIR /app
COPY --from=builder /app/dist ./dist
COPY package.json bun.lockb ./
RUN bun install --production
CMD ["bun", "run", "start"]