export enum IntegrationId {
  GOOGLE_MAPS = 'google-maps',
  PELIAS = 'pelias',
  OVERPASS = 'overpass',
  GRAPHHOPPER = 'graphhopper',
  YELP = 'yelp',
  OPENTABLE = 'opentable',
  FOURSQUARE = 'foursquare',
  MAPILLARY = 'mapillary',
  NOMINATIM = 'nominatim',
  TRIPADVISOR = 'tripadvisor',
  GEOAPIFY = 'geoapify',
  MAPBOX = 'mapbox',
  VALHALLA = 'valhalla',
  TRANSITLAND = 'transitland',
  WIKIDATA = 'wikidata',
  WIKIPEDIA = 'wikipedia',
  WIKIMEDIA = 'wikimedia',
  OPENWEATHERMAP = 'openweathermap',
  /** Observability / log shipping. System-only; configures OTLP export (e.g. Axiom). */
  AXIOM = 'axiom',
}

export enum IntegrationCapabilityId {
  SEARCH = 'search',
  SEARCH_CATEGORY = 'searchCategory',
  AUTOCOMPLETE = 'autocomplete',
  GEOCODING = 'geocoding',
  PLACE_INFO = 'placeInfo',
  ROUTING = 'routing',
  IMAGERY = 'imagery',
  MAP_ENGINE = 'mapEngine',
  MAP_LAYER = 'mapLayer',
  STREET_VIEW = 'streetView',
  TRANSIT_DATA = 'transitData',
  WEATHER = 'weather',
  LOGGING = 'logging',
}
