import { LayerType, MapEngine } from '../../schema/layers.schema'
import type { NewLayer, NewLayerGroup } from '../../schema/layers.schema'

// Helper function to get server URL when needed
function getServerUrl() {
  return process.env.SERVER_ORIGIN
}

const mapillaryAccessToken = process.env.MAPILLARY_ACCESS_TOKEN
const transitlandApiKey = process.env.TRANSITLAND_API_KEY

export const defaultLayers: Omit<
  NewLayer,
  'id' | 'userId' | 'createdAt' | 'updatedAt'
>[] = [
  {
    name: 'Mapillary Overview',
    icon: 'CameraIcon',
    showInLayerSelector: true,
    visible: false,
    type: LayerType.STREET_VIEW,
    engine: [MapEngine.MAPBOX, MapEngine.MAPLIBRE],
    groupId: 'Mapillary', // Will be replaced with actual group ID
    order: 0,
    configuration: {
      id: 'mapillary-overview',
      type: 'circle',
      source: {
        id: 'mapillary-overview',
        type: 'vector',
        tiles: [
          `https://tiles.mapillary.com/maps/vtp/mly1_computed_public/2/{z}/{x}/{y}?access_token=${mapillaryAccessToken}`,
        ],
        minzoom: 0,
        maxzoom: 5,
      },
      'source-layer': 'images',
      paint: {
        'circle-color': '#3b82f6',
        'circle-radius': 4,
        'circle-opacity': 1,
        'circle-stroke-color': '#1d4ed8',
        'circle-stroke-width': 1.5,
        'circle-stroke-opacity': 0.7,
        'circle-emissive-strength': 1,
      },
    },
  },
  {
    name: 'Mapillary Sequences',
    icon: 'CameraIcon',
    showInLayerSelector: true,
    visible: false,
    type: LayerType.STREET_VIEW,
    engine: [MapEngine.MAPBOX, MapEngine.MAPLIBRE],
    groupId: 'Mapillary',
    order: 1,
    configuration: {
      id: 'mapillary-sequence',
      type: 'line',
      slot: 'middle',
      source: {
        id: 'mapillary-sequence',
        type: 'vector',
        tiles: [
          `https://tiles.mapillary.com/maps/vtp/mly1_computed_public/2/{z}/{x}/{y}?access_token=${mapillaryAccessToken}`,
        ],
        minzoom: 6,
        maxzoom: 14,
      },
      'source-layer': 'sequence',
      paint: {
        'line-color': '#3b82f6',
        'line-opacity': [
          'interpolate',
          ['linear'],
          ['zoom'],
          6,
          0,
          14,
          1,
          22,
          0.5,
        ],
        'line-width': ['interpolate', ['linear'], ['zoom'], 6, 0, 7, 1, 14, 2],
        'line-emissive-strength': 1,
      },
      layout: {
        'line-cap': 'round',
        'line-join': 'round',
      },
    },
  },
  {
    name: 'Mapillary Images',
    icon: 'CameraIcon',
    showInLayerSelector: true,
    visible: false,
    type: LayerType.STREET_VIEW,
    engine: [MapEngine.MAPBOX, MapEngine.MAPLIBRE],
    groupId: 'Mapillary',
    order: 2,
    configuration: {
      id: 'mapillary-image',
      type: 'circle',
      slot: 'middle',
      source: {
        id: 'mapillary-image',
        type: 'vector',
        tiles: [
          `https://tiles.mapillary.com/maps/vtp/mly1_computed_public/2/{z}/{x}/{y}?access_token=${mapillaryAccessToken}`,
        ],
        minzoom: 6,
        maxzoom: 14,
      },
      'source-layer': 'image',
      paint: {
        'circle-color': '#3b82f6',
        'circle-radius': [
          'interpolate',
          ['linear'],
          ['zoom'],
          14,
          0,
          16,
          3,
          22,
          6,
        ],
        'circle-opacity': 1,
        'circle-stroke-color': '#1d4ed8',
        'circle-stroke-width': [
          'interpolate',
          ['linear'],
          ['zoom'],
          14,
          0,
          16,
          2,
        ],
        'circle-stroke-opacity': 0.7,
        'circle-emissive-strength': 1,
      },
    },
  },
  {
    name: 'CyclOSM',
    icon: 'BikeIcon',
    showInLayerSelector: true,
    visible: false,
    type: LayerType.CUSTOM,
    engine: [MapEngine.MAPBOX, MapEngine.MAPLIBRE],
    order: 3,
    configuration: {
      id: 'cyclosm',
      type: 'raster',
      slot: 'middle',
      source: {
        id: 'cyclosm',
        type: 'raster',
        tiles: [
          'https://a.tile-cyclosm.openstreetmap.fr/cyclosm-lite/{z}/{x}/{y}.png',
        ],
        tileSize: 256,
        attribution:
          '<a href="https://www.opencyclemap.org/">© OpenCycleMap</a>',
      },
      paint: {
        'raster-emissive-strength': 0.9,
        'raster-hue-rotate': 290,
        'raster-saturation': 0.3,
      },
    },
  },
  {
    name: 'Waymarked Trails',
    icon: 'BikeIcon',
    showInLayerSelector: true,
    visible: false,
    type: LayerType.CUSTOM,
    engine: [MapEngine.MAPBOX, MapEngine.MAPLIBRE],
    order: 4,
    configuration: {
      id: 'waymarkedTrails',
      type: 'raster',
      slot: 'middle',
      source: {
        id: 'waymarkedTrails',
        type: 'raster',
        tiles: ['https://tile.waymarkedtrails.org/cycling/{z}/{x}/{y}.png'],
        tileSize: 512,
        attribution:
          '<a href="https://cycling.waymarkedtrails.org/">© Waymarked Trails</a>',
      },
    },
  },
  {
    name: 'Loom Light Rail',
    icon: 'TrainIcon',
    showInLayerSelector: true,
    visible: false,
    type: LayerType.CUSTOM,
    engine: [MapEngine.MAPBOX, MapEngine.MAPLIBRE],
    groupId: 'Loom Transit',
    order: 5,
    configuration: {
      id: 'loom-light-rail',
      type: 'line',
      slot: 'middle',
      source: {
        id: 'loom-light-rail',
        type: 'vector',
        tiles: [
          `${getServerUrl()}/proxy/loom/subway-lightrail/geo/{z}/{x}/{y}`,
        ],
        maxzoom: 17,
      },
      'source-layer': 'lines',
      paint: {
        'line-color': ['concat', '#', ['get', 'color']],
        'line-width': 5,
        'line-opacity': 1,
        'line-emissive-strength': 1,
        'line-occlusion-opacity': 0.15,
      },
      layout: {
        'line-cap': 'round',
        'line-join': 'round',
      },
    },
  },
  {
    name: 'Loom Tram',
    icon: 'TrainIcon',
    showInLayerSelector: true,
    visible: false,
    type: LayerType.CUSTOM,
    engine: [MapEngine.MAPBOX, MapEngine.MAPLIBRE],
    groupId: 'Loom Transit',
    order: 6,
    configuration: {
      id: 'loom-tram',
      type: 'line',
      slot: 'middle',
      source: {
        id: 'loom-tram',
        type: 'vector',
        tiles: [`${getServerUrl()}/proxy/loom/tram/geo/{z}/{x}/{y}`],
        maxzoom: 17,
      },
      'source-layer': 'lines',
      paint: {
        'line-color': ['concat', '#', ['get', 'color']],
        'line-width': 5,
        'line-opacity': 1,
        'line-emissive-strength': 1,
        'line-occlusion-opacity': 0.15,
      },
      layout: {
        'line-cap': 'round',
        'line-join': 'round',
      },
    },
  },
  {
    name: 'Loom Rail (Commuter)',
    icon: 'TrainIcon',
    showInLayerSelector: true,
    visible: false,
    type: LayerType.CUSTOM,
    engine: [MapEngine.MAPBOX, MapEngine.MAPLIBRE],
    groupId: 'Loom Transit',
    order: 7,
    configuration: {
      id: 'loom-rail-commuter',
      type: 'line',
      slot: 'middle',
      source: {
        id: 'loom-rail-commuter',
        type: 'vector',
        tiles: [`${getServerUrl()}/proxy/loom/rail-commuter/geo/{z}/{x}/{y}`],
        maxzoom: 17,
      },
      'source-layer': 'lines',
      paint: {
        'line-color': ['concat', '#', ['get', 'color']],
        'line-width': 5,
        'line-opacity': 1,
        'line-emissive-strength': 1,
        'line-occlusion-opacity': 0.15,
      },
      layout: {
        'line-cap': 'round',
        'line-join': 'round',
      },
    },
  },
  {
    name: 'Loom Rail (Long Distance)',
    icon: 'TrainIcon',
    showInLayerSelector: true,
    visible: false,
    type: LayerType.CUSTOM,
    engine: [MapEngine.MAPBOX, MapEngine.MAPLIBRE],
    groupId: 'Loom Transit',
    order: 8,
    configuration: {
      id: 'loom-rail',
      type: 'line',
      slot: 'middle',
      source: {
        id: 'loom-rail',
        type: 'vector',
        tiles: [`${getServerUrl()}/proxy/loom/rail/geo/{z}/{x}/{y}`],
        maxzoom: 17,
      },
      'source-layer': 'lines',
      paint: {
        'line-color': ['concat', '#', ['get', 'color']],
        'line-width': 5,
        'line-opacity': 1,
        'line-emissive-strength': 1,
        'line-occlusion-opacity': 0.15,
      },
      layout: {
        'line-cap': 'round',
        'line-join': 'round',
      },
    },
  },
  {
    name: 'Transitland',
    icon: 'TrainIcon',
    showInLayerSelector: true,
    visible: false,
    type: LayerType.CUSTOM,
    engine: [MapEngine.MAPBOX, MapEngine.MAPLIBRE],
    order: 9,
    configuration: {
      id: 'transitland',
      type: 'line',
      slot: 'middle',
      source: {
        id: 'transitland',
        type: 'vector',
        tiles: [
          `https://transit.land/api/v2/tiles/routes/tiles/{z}/{x}/{y}.pbf?apikey=${transitlandApiKey}`,
        ],
        maxzoom: 14,
      },
      'source-layer': 'routes',
      layout: {
        'line-cap': 'round',
        'line-join': 'round',
        'symbol-placement': 'line',
        'text-field': ['get', 'route_long_name'],
        'text-size': 12,
        'text-offset': [0, 1],
      },
      paint: {
        'line-width': ['interpolate', ['linear'], ['zoom'], 12, 1, 18, 6],
        'line-color': [
          'match',
          ['get', 'route_type'],
          0,
          ['coalesce', ['get', 'route_color'], 'blue'],
          1,
          ['coalesce', ['get', 'route_color'], 'blue'],
          2,
          'red',
          3,
          ['coalesce', ['get', 'route_color'], 'lightblue'],
          4,
          'blue',
          5,
          'purple',
          6,
          'pink',
          7,
          'brown',
          11,
          'black',
          12,
          'red',
          'grey',
        ],
        'line-occlusion-opacity': 0.15,
        'line-emissive-strength': 1,
      },
    },
  },
  {
    name: 'Mapbox traffic',
    icon: 'CarFrontIcon',
    showInLayerSelector: true,
    visible: false,
    type: LayerType.CUSTOM,
    engine: [MapEngine.MAPBOX],
    order: 10,
    configuration: {
      id: 'traffic',
      type: 'line',
      slot: 'middle',
      source: {
        id: 'traffic',
        type: 'vector',
        url: 'mapbox://mapbox.mapbox-traffic-v1',
        attribution: 'Mapbox',
      },
      'source-layer': 'traffic',
      layout: {
        'line-cap': 'round',
        'line-join': 'round',
      },
      paint: {
        'line-width': ['interpolate', ['linear'], ['zoom'], 14, 2, 20, 7],
        'line-offset': ['interpolate', ['linear'], ['zoom'], 14, 0, 20, 2],
        'line-color': [
          'match',
          ['get', 'congestion'],
          'low',
          '#1A9641',
          'moderate',
          '#EED322',
          'heavy',
          '#E6B71E',
          'severe',
          '#DA3838',
          '#000000',
        ],
        'line-opacity': 0.8,
        'line-occlusion-opacity': 0.15,
        'line-emissive-strength': 1,
      },
    },
  },
  {
    name: 'Hillshade',
    icon: 'MountainSnowIcon',
    showInLayerSelector: true,
    visible: false,
    type: LayerType.CUSTOM,
    engine: [MapEngine.MAPBOX],
    groupId: 'Terrain',
    order: 11,
    configuration: {
      id: 'hillshade',
      type: 'hillshade',
      source: {
        id: 'terrain-rgb',
        type: 'raster-dem',
        url: 'mapbox://mapbox.mapbox-terrain-dem-v1',
      },
      paint: {
        'hillshade-shadow-color': '#0f172a',
        'hillshade-highlight-color': '#fef3c7',
        'hillshade-accent-color': '#fcd34d',
        'hillshade-illumination-direction': 315,
        'hillshade-exaggeration': 1,
      },
    },
  },
  {
    name: 'Contours',
    icon: 'MountainSnowIcon',
    showInLayerSelector: true,
    visible: false,
    type: LayerType.CUSTOM,
    engine: [MapEngine.MAPBOX],
    groupId: 'Terrain',
    order: 12,
    configuration: {
      id: 'contours',
      type: 'line',
      source: {
        id: 'contours',
        type: 'vector',
        url: 'mapbox://mapbox.mapbox-terrain-v2',
      },
      'source-layer': 'contour',
      paint: {
        'line-color': '#334155',
        'line-width': ['interpolate', ['linear'], ['zoom'], 11, 0.5, 16, 1],
        'line-opacity': ['interpolate', ['linear'], ['zoom'], 11, 0.5, 16, 0.8],
      },
      layout: {
        'line-join': 'round',
      },
    },
  },
  {
    name: 'Contour Labels',
    icon: 'MountainSnowIcon',
    showInLayerSelector: true,
    visible: false,
    type: LayerType.CUSTOM,
    engine: [MapEngine.MAPBOX],
    groupId: 'Terrain',
    order: 13,
    configuration: {
      id: 'contour-labels',
      type: 'symbol',
      source: {
        id: 'contours',
        type: 'vector',
        url: 'mapbox://mapbox.mapbox-terrain-v2',
      },
      'source-layer': 'contour',
      paint: {
        'text-color': '#334155',
        'text-halo-color': '#ffffff',
        'text-halo-width': 1,
      },
      layout: {
        'symbol-placement': 'line',
        'text-field': ['concat', ['get', 'ele'], 'm'],
        'text-font': ['DIN Pro Medium', 'Arial Unicode MS Regular'],
        'text-size': 10,
        'text-letter-spacing': 0.1,
        'text-max-angle': 30,
        'text-padding': 5,
        'text-spacing': 500,
      },
    },
  },
]

export const defaultLayerGroups: Omit<
  NewLayerGroup,
  'id' | 'userId' | 'createdAt' | 'updatedAt'
>[] = [
  {
    name: 'Mapillary',
    icon: 'CameraIcon',
    showInLayerSelector: true,
    visible: false,
    order: 0,
  },
  {
    name: 'Loom Transit',
    icon: 'TrainIcon',
    showInLayerSelector: true,
    visible: false,
    order: 1,
  },
  {
    name: 'Terrain',
    icon: 'MountainSnowIcon',
    showInLayerSelector: true,
    visible: false,
    order: 2,
  },
]
