/**
 * Dump the OpenAPI spec to a static file.
 *
 * The docs site used to build its API reference by fetching `/docs/json` off a
 * running Parchment instance, which meant the reference could only be
 * regenerated by hand, on a machine that happened to have the server up. This
 * script produces the same document with no server, no database and no
 * network: it mounts the controllers onto a bare Elysia app purely so the
 * swagger plugin can walk them, then asks that app for its own spec in-process.
 *
 * Only the route surface matters here, so none of the runtime startup work
 * (crypto env checks, OTel, realtime bootstrap, permission sync) is repeated —
 * which is exactly what makes it safe to run in CI.
 *
 * Usage: bun scripts/generate-openapi.ts [outfile]
 */

import { Elysia } from 'elysia'
import { swagger } from '@elysiajs/swagger'
import { swagger as swaggerConfig } from '../src/config'
import * as controllers from '../src/controllers'

const OUTFILE = process.argv[2] ?? 'openapi.json'

/** Every Elysia sub-app exported from the controllers barrel. */
function controllerApps(): Elysia[] {
  return Object.entries(controllers)
    .filter(([, value]) => value instanceof Elysia)
    .map(([, value]) => value as Elysia)
}

const app = new Elysia().use(swagger(swaggerConfig))
for (const controller of controllerApps()) app.use(controller)

const response = await app.handle(
  new Request('http://localhost/docs/json'),
)

if (!response.ok) {
  console.error(`Failed to render the spec: HTTP ${response.status}`)
  process.exit(1)
}

const spec = (await response.json()) as {
  paths?: Record<string, unknown>
  tags?: unknown[]
}

const pathCount = Object.keys(spec.paths ?? {}).length
if (pathCount === 0) {
  // An empty document would sail through the docs build and silently delete
  // every API page, so treat it as a failure rather than write it out.
  console.error('Rendered spec contains no paths — refusing to write it')
  process.exit(1)
}

// Stable key order so an unrelated change can't produce a spurious diff.
await Bun.write(OUTFILE, JSON.stringify(spec, null, 2) + '\n')

console.log(
  `Wrote ${OUTFILE} — ${pathCount} paths across ${spec.tags?.length ?? 0} tags`,
)
