# Build stage
FROM oven/bun:latest AS builder
WORKDIR /app/web
COPY web/package.json web/bun.lockb* ./
RUN bun install
COPY web/. ./
COPY server/src/types /app/server/src/types
RUN bun run build

# Production stage
# TODO: Use bun or nginx for this instead?
FROM node:18 AS production
WORKDIR /app
RUN npm install -g http-server
COPY --from=builder /app/web/dist /app/dist
ENV VITE_PORT=5173
EXPOSE ${VITE_PORT}

CMD http-server /app/dist -p ${VITE_PORT} --host 0.0.0.0
